import type { Skill } from "./index";

export const COLUMN_SKILLS: Skill[] = [
  // ==========================================
  // PENJUMLAHAN BERSUSUN
  // ==========================================
  {
    id: "add-column-no-regroup",
    operation: "addition",
    title: "Penjumlahan Bersusun Tanpa Menyimpan",
    subtitle: "Menjumlahkan kolom demi kolom dari satuan ke puluhan lurus ke bawah",
    description: "Teknik menyusun bilangan secara vertikal lurus nilai tempatnya: satuan dijumlahkan dengan satuan, puluhan dengan puluhan tanpa ada angka simpanan.",
    prerequisites: ["add-two-digit"],
    representations: ["column-arithmetic", "place-value"],
    difficulty: 2,
    conceptTitle: "Susun Lurus Satuan dan Puluhan",
    conceptExplanation: "Tuliskan bilangan bersusun ke bawah. Luruskan angka satuan dengan satuan, dan puluhan dengan puluhan. Hitung dari sebelah kanan (satuan) terlebih dahulu: 4 + 3 = 7, lalu 2 + 1 = 3. Hasilnya 37.",
    exampleA: 24,
    exampleB: 13,
    strategy: "column-no-regroup",
    objectType: "pencil",
    mathForm: {
      title: "Format Penjumlahan Bersusun Pendek",
      standardExpression: "24 + 13 = 37",
      terms: [
        { term: "24", role: "Bilangan Atas", explanation: "2 puluhan (20) dan 4 satuan." },
        { term: "13", role: "Bilangan Bawah", explanation: "1 puluhan (10) dan 3 satuan." },
        { term: "+", role: "Tanda Jumlah", explanation: "Operasi penjumlahan dari kanan ke kiri." },
        { term: "37", role: "Jumlah Total", explanation: "Hasil penjumlahan kolom satuan (7) dan puluhan (3)." },
      ],
      note: "Selalu jumlahkan dari kolom paling kanan (satuan) sebelum berpindah ke kolom puluhan.",
    },
    guidedPractice: {
      prompt: "Ada 32 pensil hitam dan 15 pensil biru di tempat pensil. Berapa jumlah seluruh pensil?",
      a: 32,
      b: 15,
      answer: 47,
      hint: "Kolom satuan: 2 + 5 = 7. Kolom puluhan: 3 + 1 = 4. Gabungkan hasilnya!",
      objectType: "pencil",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: 2-Digit Kecil",
        title: "Koleksi Pensil: 23 + 14",
        context: "Ada 23 pensil kayu dan 14 pensil warna. Luruskan satuan 3 + 4 = 7, lalu puluhan 2 + 1 = 3.",
        a: 23,
        b: 14,
        objectType: "pencil",
        standardExpression: "23 + 14 = 37",
        explanationNote: "Satuan 3 + 4 = 7, puluhan 2 + 1 = 3 -> Total 37 batang pensil.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: 2-Digit dengan 1-Digit",
        title: "Tumpukan Buku Cerita: 42 + 5",
        context: "Perpustakaan memiliki 42 buku ensiklopedia dan mendapat sumbangan 5 buku baru.",
        a: 42,
        b: 5,
        objectType: "book",
        standardExpression: "42 + 5 = 47",
        explanationNote: "Luruskan angka 5 tepat di bawah angka 2 (satuan). 2 + 5 = 7, puluhan tetap 4 -> 47 buku.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: 3-Digit Tanpa Simpan",
        title: "Keranjang Telur: 142 + 235",
        context: "Peternak mengumpulkan 142 telur ayam dan 235 telur bebek dari kandang.",
        a: 142,
        b: 235,
        objectType: "egg",
        standardExpression: "142 + 235 = 377",
        explanationNote: "Satuan: 2 + 5 = 7. Puluhan: 4 + 3 = 7. Ratusan: 1 + 2 = 3. Total 377 butir telur.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Berakhiran Nol",
        title: "Kelereng Kotak: 50 + 26",
        context: "Ada 50 kelereng biru di toples besar dan 26 kelereng merah di kantong kain.",
        a: 50,
        b: 26,
        objectType: "marble",
        standardExpression: "50 + 26 = 76",
        explanationNote: "Satuan: 0 + 6 = 6. Puluhan: 5 + 2 = 7 -> Total 76 butir kelereng.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Buku Perpustakaan Desa",
        story: "Perpustakaan desa memiliki 34 buku dongeng nusantara dan membeli 23 buku sains anak.",
        question: "Berapa total buku yang ada di perpustakaan sekarang?",
        a: 34,
        b: 23,
        answer: 57,
        objectType: "book",
        hint: "Susun bersusun: Satuan 4 + 3 = 7, Puluhan 3 + 2 = 5.",
        explanation: "34 buku + 23 buku = 57 buku.",
      },
      {
        id: "sp-2",
        title: "Kue Pesta Sekolah",
        story: "Ibu guru menyiapkan 51 kotak susu stroberi dan 36 kotak susu vanila untuk kegiatan pramuka.",
        question: "Berapa kotak susu yang disiapkan seluruhnya?",
        a: 51,
        b: 36,
        answer: 87,
        objectType: "cookie",
        hint: "Satuan: 1 + 6 = 7. Puluhan: 5 + 3 = 8.",
        explanation: "51 kotak + 36 kotak = 87 kotak susu.",
      },
      {
        id: "sp-3",
        title: "Panen Jeruk Kebun Paman",
        story: "Paman memetik 45 buah jeruk manis di pagi hari dan 32 buah jeruk di sore hari.",
        question: "Berapa butir jeruk yang dipetik paman hari ini?",
        a: 45,
        b: 32,
        answer: 77,
        objectType: "orange",
        hint: "Susun ke bawah: 5 + 2 = 7 di satuan, 4 + 3 = 7 di puluhan.",
        explanation: "45 jeruk + 32 jeruk = 77 buah jeruk.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Penjumlahan Bersusun Tanpa Menyimpan",
      instructions: "Hitunglah penjumlahan bersusun berikut mulai dari kolom satuan (kanan) ke puluhan (kiri).",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "direct",
          question: "Hitung hasil penjumlahan bersusun: 25 + 14 = ...",
          a: 25,
          b: 14,
          answer: 39,
          hint: "Satuan 5 + 4 = 9, puluhan 2 + 1 = 3.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "story",
          storyText: "Adik memiliki 31 kelereng hijau dan mendapat 18 kelereng kuning dari kakak.",
          question: "Berapa banyak kelereng adik sekarang?",
          a: 31,
          b: 18,
          answer: 49,
          objectType: "marble",
          hint: "31 + 18: 1 + 8 = 9, 3 + 1 = 4.",
        },
        {
          id: "ws-3",
          number: 3,
          type: "direct",
          question: "Hitung hasil penjumlahan bersusun: 52 + 36 = ...",
          a: 52,
          b: 36,
          answer: 88,
          hint: "2 + 6 = 8, 5 + 3 = 8.",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitung penjumlahan 3-digit: 123 + 245 = ...",
          a: 123,
          b: 245,
          answer: 368,
          hint: "Satuan 3+5=8, puluhan 2+4=6, ratusan 1+2=3.",
        },
        {
          id: "ws-5",
          number: 5,
          type: "story",
          storyText: "Toko buku memiliki 60 buku tulis dan menerima kiriman baru 25 buku tulis.",
          question: "Berapa total buku tulis di toko sekarang?",
          a: 60,
          b: 25,
          answer: 85,
          objectType: "book",
          hint: "0 + 5 = 5, 6 + 2 = 8.",
        },
      ],
    },
  },

  {
    id: "add-column-regroup",
    operation: "addition",
    title: "Penjumlahan Bersusun Dengan Menyimpan",
    subtitle: "Menyimpan 1 puluhan ke kolom sebelah kiri jika hasil satuan 10 atau lebih",
    description: "Ketika jumlah angka pada kolom satuan bernilai 10 atau lebih, tulis angka satuan di bawah dan simpan angka puluhan (1) di atas kolom puluhan untuk dijumlahkan berikutnya.",
    prerequisites: ["add-column-no-regroup"],
    representations: ["column-arithmetic", "base-ten"],
    difficulty: 3,
    conceptTitle: "Aturan Menyimpan (Nilai Tempat 10)",
    conceptExplanation: "38 + 27: Pada kolom satuan, 8 + 7 = 15. Angka 15 memiliki 1 puluhan dan 5 satuan. Tulis 5 di bawah kolom satuan, lalu simpan angka 1 kecil di atas kolom puluhan. Kemudian jumlahkan puluhan: 1 (simpanan) + 3 + 2 = 6. Hasilnya 65.",
    exampleA: 38,
    exampleB: 27,
    strategy: "column-regroup",
    objectType: "orange",
    mathForm: {
      title: "Penjumlahan Bersusun dengan Angka Simpanan",
      standardExpression: "38 + 27 = 65",
      terms: [
        { term: "38", role: "Bilangan Atas", explanation: "3 puluhan dan 8 satuan." },
        { term: "27", role: "Bilangan Bawah", explanation: "2 puluhan dan 7 satuan." },
        { term: "1 (simpanan)", role: "Simpanan Puluhan", explanation: "Dari 8 + 7 = 15 (1 puluhan disimpan di atas)." },
        { term: "65", role: "Hasil Akhir", explanation: "Satuan = 5, puluhan = 1 + 3 + 2 = 6." },
      ],
      note: "Jangan lupa menambahkan angka 1 simpanan saat menghitung kolom puluhan.",
    },
    guidedPractice: {
      prompt: "Hitunglah 47 + 25 dengan penjumlahan bersusun menyimpan.",
      a: 47,
      b: 25,
      answer: 72,
      hint: "Kolom satuan: 7 + 5 = 12 (tulis 2, simpan 1). Kolom puluhan: 1 + 4 + 2 = 7.",
      objectType: "orange",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Simpan ke Puluhan",
        title: "Keranjang Jeruk: 28 + 15",
        context: "Ada 28 jeruk manis dan 15 jeruk bali. Satuan 8 + 5 = 13 (tulis 3, simpan 1). Puluhan: 1 + 2 + 1 = 4.",
        a: 28,
        b: 15,
        objectType: "orange",
        standardExpression: "28 + 15 = 43",
        explanationNote: "Hasil akhir adalah 43 buah jeruk.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Simpan ke Ratusan",
        title: "Panen Apel Merah: 85 + 43",
        context: "Kebun pertama menghasilkan 85 apel, kebun kedua 43 apel. Satuan 5 + 3 = 8. Puluhan 8 + 4 = 12 (tulis 2, simpan 1 ke ratusan).",
        a: 85,
        b: 43,
        objectType: "apple",
        standardExpression: "85 + 43 = 128",
        explanationNote: "Simpanan puluhan menjadi ratusan baru: 128 buah apel.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Simpan Bertingkat 3-Digit",
        title: "Biskuit Cokelat Toko: 267 + 185",
        context: "Satuan 7 + 5 = 12 (tulis 2, simpan 1). Puluhan 1 + 6 + 8 = 15 (tulis 5, simpan 1). Ratusan 1 + 2 + 1 = 4.",
        a: 267,
        b: 185,
        objectType: "cookie",
        standardExpression: "267 + 185 = 452",
        explanationNote: "Dua kali menyimpan (ke puluhan dan ke ratusan) menghasilkan 452 keping biskuit.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Jumlah Pas Sepuluh",
        title: "Pensil Warna Ujian: 46 + 24",
        context: "Satuan 6 + 4 = 10 (tulis 0 di satuan, simpan 1 di puluhan). Puluhan: 1 + 4 + 2 = 7.",
        a: 46,
        b: 24,
        objectType: "pencil",
        standardExpression: "46 + 24 = 70",
        explanationNote: "Kolom satuan bernilai 0 karena pas sepuluh: total 70 pensil.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Donasi Buku Sekolah",
        story: "Siswa kelas 2A mengumpulkan 38 buku cerita, sedangkan kelas 2B mengumpulkan 47 buku ensiklopedia.",
        question: "Berapa seluruh buku yang terkumpul dari kedua kelas?",
        a: 38,
        b: 47,
        answer: 85,
        objectType: "book",
        hint: "Satuan: 8 + 7 = 15 (tulis 5, simpan 1). Puluhan: 1 + 3 + 4 = 8.",
        explanation: "38 buku + 47 buku = 85 buku bacaan.",
      },
      {
        id: "sp-2",
        title: "Panen Telur Ayam",
        story: "Paman mengumpulkan 56 butir telur di pagi hari dan 39 butir telur di sore hari.",
        question: "Berapa total telur yang dipanen paman hari ini?",
        a: 56,
        b: 39,
        answer: 95,
        objectType: "egg",
        hint: "Satuan 6 + 9 = 15 (tulis 5, simpan 1). Puluhan: 1 + 5 + 3 = 9.",
        explanation: "56 butir + 39 butir = 95 butir telur.",
      },
      {
        id: "sp-3",
        title: "Kue Ulang Tahun",
        story: "Ibu memanggang 48 kue bolu pandan dan 28 kue bolu cokelat untuk bazar sekolah.",
        question: "Berapa total kue bolu yang dipanggang ibu?",
        a: 48,
        b: 28,
        answer: 76,
        objectType: "cookie",
        hint: "8 + 8 = 16 (tulis 6 simpan 1). 1 + 4 + 2 = 7.",
        explanation: "48 kue + 28 kue = 76 kue bolu.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Penjumlahan Bersusun Dengan Menyimpan",
      instructions: "Jumlahkan kolom satuan terlebih dahulu. Jika hasilnya 10 atau lebih, tulis angka satuannya dan simpan 1 di atas kolom puluhan.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "direct",
          question: "Hitung hasil penjumlahan bersusun: 37 + 26 = ...",
          a: 37,
          b: 26,
          answer: 63,
          hint: "Satuan 7 + 6 = 13 (tulis 3 simpan 1). Puluhan 1 + 3 + 2 = 6.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "story",
          storyText: "Pak tani memetik 49 semangka besar dan 35 semangka kecil.",
          question: "Berapa banyak semangka yang dipetik pak tani?",
          a: 49,
          b: 35,
          answer: 84,
          objectType: "orange",
          hint: "9 + 5 = 14 (tulis 4 simpan 1). 1 + 4 + 3 = 8.",
        },
        {
          id: "ws-3",
          number: 3,
          type: "direct",
          question: "Hitung hasil penjumlahan bersusun: 58 + 27 = ...",
          a: 58,
          b: 27,
          answer: 85,
          hint: "8 + 7 = 15 (simpan 1). 1 + 5 + 2 = 8.",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitung penjumlahan 3-digit dengan menyimpan: 174 + 258 = ...",
          a: 174,
          b: 258,
          answer: 432,
          hint: "4+8=12 (simpan 1). 1+7+5=13 (simpan 1). 1+1+2=4.",
        },
        {
          id: "ws-5",
          number: 5,
          type: "story",
          storyText: "Koperasi sekolah memiliki 65 buku tulis bergaris dan 48 buku gambar.",
          question: "Berapa jumlah buku di koperasi seluruhnya?",
          a: 65,
          b: 48,
          answer: 113,
          objectType: "book",
          hint: "5 + 8 = 13 (simpan 1). 1 + 6 + 4 = 11.",
        },
      ],
    },
  },

  // ==========================================
  // PENGURANGAN BERSUSUN
  // ==========================================
  {
    id: "sub-column-no-regroup",
    operation: "subtraction",
    title: "Pengurangan Bersusun Tanpa Meminjam",
    subtitle: "Mengurangkan kolom vertikal mulai dari satuan ke puluhan tanpa perlu meminjam",
    description: "Menyusun bilangan lurus nilai tempatnya, kemudian mengurangkan angka atas dengan angka bawah mulai dari kolom satuan lalu kolom puluhan.",
    prerequisites: ["sub-bridge-ten"],
    representations: ["column-arithmetic", "place-value"],
    difficulty: 2,
    conceptTitle: "Kurangkan Kolom Satuan Lalu Puluhan",
    conceptExplanation: "48 − 25: Luruskan angka. Kurangkan kolom satuan dari kanan: 8 − 5 = 3. Tulis 3 di bawah. Lanjut kolom puluhan: 4 − 2 = 2. Tulis 2 di bawah. Hasilnya 23.",
    exampleA: 48,
    exampleB: 25,
    strategy: "column-no-regroup",
    objectType: "cookie",
    mathForm: {
      title: "Format Pengurangan Bersusun Pendek",
      standardExpression: "48 − 25 = 23",
      terms: [
        { term: "48", role: "Bilangan Awal", explanation: "4 puluhan (40) dan 8 satuan." },
        { term: "25", role: "Bilangan Pengurang", explanation: "2 puluhan (20) dan 5 satuan." },
        { term: "−", role: "Tanda Kurang", explanation: "Operasi selisih/pengurangan." },
        { term: "23", role: "Sisa Pengurangan", explanation: "Satuan: 8 − 5 = 3, Puluhan: 4 − 2 = 2." },
      ],
      note: "Pastikan selalu mengurangi angka atas dengan angka bawah secara vertikal.",
    },
    guidedPractice: {
      prompt: "Ada 39 butir biskuit di toples. Dimakan 14 butir. Berapa butir biskuit yang tersisa?",
      a: 39,
      b: 14,
      answer: 25,
      hint: "Kolom satuan: 9 − 4 = 5. Kolom puluhan: 3 − 1 = 2.",
      objectType: "cookie",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Puluhan Genap",
        title: "Biskuit Toples: 48 − 25",
        context: "Ada 48 keping biskuit. Sebanyak 25 keping dibagikan ke teman. Kurangkan 8 − 5 = 3, lalu 4 − 2 = 2.",
        a: 48,
        b: 25,
        objectType: "cookie",
        standardExpression: "48 − 25 = 23",
        explanationNote: "Tersisa 23 keping biskuit enak di toples.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: 2-Digit Dikurang 1-Digit",
        title: "Koleksi Pensil: 37 − 5",
        context: "Paman membawa 37 pensil dan memberikan 5 pensil kepada adik. Satuan: 7 − 5 = 2, puluhan tetap 3.",
        a: 37,
        b: 5,
        objectType: "pencil",
        standardExpression: "37 − 5 = 32",
        explanationNote: "Tersisa 32 batang pensil.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: 3-Digit Tanpa Pinjam",
        title: "Stok Buku Gudang: 365 − 142",
        context: "Satuan 5 − 2 = 3. Puluhan 6 − 4 = 2. Ratusan 3 − 1 = 2. Total sisa 223 buku.",
        a: 365,
        b: 142,
        objectType: "book",
        standardExpression: "365 − 142 = 223",
        explanationNote: "Tersisa 223 buku bacaan di gudang.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Satuan Sama Menjadi Nol",
        title: "Kantong Kelereng: 58 − 28",
        context: "Satuan 8 − 8 = 0. Puluhan 5 − 2 = 3. Hasil akhirnya 30.",
        a: 58,
        b: 28,
        objectType: "marble",
        standardExpression: "58 − 28 = 30",
        explanationNote: "Kolom satuan menghasilkan angka 0.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Jeruk di Kios Buah",
        story: "Pedagang buah memiliki 57 buah jeruk di kiosnya. Sebanyak 24 buah jeruk laku terjual.",
        question: "Berapa buah jeruk yang belum terjual?",
        a: 57,
        b: 24,
        answer: 33,
        objectType: "orange",
        hint: "Satuan 7 − 4 = 3. Puluhan 5 − 2 = 3.",
        explanation: "57 jeruk − 24 jeruk = 33 buah jeruk.",
      },
      {
        id: "sp-2",
        title: "Buku Tulis Siswa",
        story: "Koperasi sekolah menyiapkan 68 buku tulis. Sebanyak 35 buku telah dibeli siswa kelas 3.",
        question: "Berapa sisa buku tulis yang masih ada di koperasi?",
        a: 68,
        b: 35,
        answer: 33,
        objectType: "book",
        hint: "8 − 5 = 3 pada satuan, 6 − 3 = 3 pada puluhan.",
        explanation: "68 buku − 35 buku = 33 buku tulis.",
      },
      {
        id: "sp-3",
        title: "Kue Kering Lebaran",
        story: "Nenek membuat 49 kue kering nastar. Sebanyak 16 kue disajikan untuk tamu yang berkunjung.",
        question: "Berapa banyak kue nastar yang masih tersimpan?",
        a: 49,
        b: 16,
        answer: 33,
        objectType: "cookie",
        hint: "9 − 6 = 3 di satuan, 4 − 1 = 3 di puluhan.",
        explanation: "49 kue − 16 kue = 33 kue nastar.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Pengurangan Bersusun Tanpa Meminjam",
      instructions: "Kurangkan angka secara bersusun ke bawah mulai dari satuan lalu puluhan.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "direct",
          question: "Hitung pengurangan bersusun: 46 − 23 = ...",
          a: 46,
          b: 23,
          answer: 23,
          hint: "6 − 3 = 3, 4 − 2 = 2.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "story",
          storyText: "Paman memiliki 78 butir telur bebek dan menjual 36 butir ke pasar.",
          question: "Berapa butir telur bebek yang tersisa?",
          a: 78,
          b: 36,
          answer: 42,
          objectType: "egg",
          hint: "8 − 6 = 2, 7 − 3 = 4.",
        },
        {
          id: "ws-3",
          number: 3,
          type: "direct",
          question: "Hitung pengurangan bersusun: 85 − 41 = ...",
          a: 85,
          b: 41,
          answer: 44,
          hint: "5 − 1 = 4, 8 − 4 = 4.",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitung pengurangan 3-digit: 259 − 134 = ...",
          a: 259,
          b: 134,
          answer: 125,
          hint: "9−4=5, 5−3=2, 2−1=1.",
        },
        {
          id: "ws-5",
          number: 5,
          type: "story",
          storyText: "Di rak buku terdapat 96 buku bacaan. Sebanyak 50 buku dipinjam siswa.",
          question: "Berapa buku bacaan yang masih ada di rak?",
          a: 96,
          b: 50,
          answer: 46,
          objectType: "book",
          hint: "6 − 0 = 6, 9 − 5 = 4.",
        },
      ],
    },
  },

  {
    id: "sub-column-regroup",
    operation: "subtraction",
    title: "Pengurangan Bersusun Dengan Meminjam",
    subtitle: "Meminjam 1 puluhan (10 satuan) jika angka atas lebih kecil dari angka bawah",
    description: "Jika angka yang dikurangi lebih kecil dari pengurang pada suatu kolom, pinjam 1 dari kolom sebelah kiri. Nilai yang dipinjam bernilai 10 di kolom tersebut.",
    prerequisites: ["sub-column-no-regroup"],
    representations: ["column-arithmetic", "base-ten"],
    difficulty: 3,
    conceptTitle: "Teknik Meminjam Nilai Tempat",
    conceptExplanation: "52 − 27: Pada kolom satuan, 2 tidak bisa dikurangi 7. Pinjam 1 puluhan dari 5 (puluhan 5 dicoret menjadi 4). 1 puluhan = 10 satuan, sehingga satuan 2 menjadi 12. Sekarang hitung: 12 − 7 = 5. Pada kolom puluhan: 4 − 2 = 2. Hasil akhirnya 25.",
    exampleA: 52,
    exampleB: 27,
    strategy: "column-regroup",
    objectType: "marble",
    mathForm: {
      title: "Pengurangan Bersusun dengan Teknik Meminjam",
      standardExpression: "52 − 27 = 25",
      terms: [
        { term: "52", role: "Bilangan Awal", explanation: "5 puluhan (dipinjam 1 menjadi 4) dan 2 satuan (menjadi 12)." },
        { term: "27", role: "Bilangan Pengurang", explanation: "2 puluhan dan 7 satuan." },
        { term: "12 − 7 = 5", role: "Hasil Kolom Satuan", explanation: "Satuan setelah dipinjam 10 menjadi 12 dikurangi 7." },
        { term: "4 − 2 = 2", role: "Hasil Kolom Puluhan", explanation: "Sisa 4 puluhan dikurangi 2 puluhan." },
      ],
      note: "Coret angka yang dipinjam dan tuliskan angka barunya di atas agar tidak lupa.",
    },
    guidedPractice: {
      prompt: "Hitunglah 63 − 28 dengan pengurangan bersusun meminjam.",
      a: 63,
      b: 28,
      answer: 35,
      hint: "3 tidak bisa dikurang 8. Pinjam 1 dari 6 (menjadi 5). 3 menjadi 13. 13 − 8 = 5. Puluhan: 5 − 2 = 3.",
      objectType: "pencil",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Pinjam dari Puluhan",
        title: "Kelereng Mainan: 52 − 27",
        context: "Ada 52 butir kelereng. Diberikan 27 butir kepada adik. Satuan: pinjam 1 puluhan, 12 − 7 = 5. Puluhan: 4 − 2 = 2.",
        a: 52,
        b: 27,
        objectType: "marble",
        standardExpression: "52 − 27 = 25",
        explanationNote: "Tersisa 25 butir kelereng.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Pinjam dari Ratusan",
        title: "Buku Cerita Bergambar: 324 − 182",
        context: "Satuan: 4 − 2 = 2. Puluhan: 2 tidak bisa dikurang 8, pinjam 1 dari ratusan 3 (menjadi 2). 12 − 8 = 4. Ratusan: 2 − 1 = 1.",
        a: 324,
        b: 182,
        objectType: "book",
        standardExpression: "324 − 182 = 142",
        explanationNote: "Meminjam dari kolom ratusan menghasilkan 142 buku.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Meminjam Melewati Angka Nol",
        title: "Keranjang Telur: 304 − 158",
        context: "Satuan 4 butuh pinjam. Puluhan 0 tidak bisa dipinjam langsung, maka pinjam dari ratusan 3 (menjadi 2), puluhan jadi 9, satuan jadi 14. 14 − 8 = 6, 9 − 5 = 4, 2 − 1 = 1.",
        a: 304,
        b: 158,
        objectType: "egg",
        standardExpression: "304 − 158 = 146",
        explanationNote: "Teknik meminjam melewati nol menghasilkan 146 butir telur.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Pinjam Bertingkat Puluhan & Satuan",
        title: "Apel Segar Petani: 432 − 175",
        context: "Satuan: 12 − 5 = 7. Puluhan: sisa 2 pinjam dari 4 (menjadi 3), 12 − 7 = 5. Ratusan: 3 − 1 = 2.",
        a: 432,
        b: 175,
        objectType: "apple",
        standardExpression: "432 − 175 = 257",
        explanationNote: "Dua kali meminjam menghasilkan 257 buah apel.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Koleksi Pensil Warna",
        story: "Budi memiliki 61 pensil warna. Ia meminjamkan 25 pensil warna kepada teman sekelasnya saat lomba mewarnai.",
        question: "Berapa banyak pensil warna milik Budi yang masih tersisa?",
        a: 61,
        b: 25,
        answer: 36,
        objectType: "pencil",
        hint: "1 tidak bisa dikurang 5. Pinjam 1 dari 6 (tersisa 5). 11 − 5 = 6. 5 − 2 = 3.",
        explanation: "61 pensil − 25 pensil = 36 pensil warna.",
      },
      {
        id: "sp-2",
        title: "Jeruk Manis Pedagang",
        story: "Pak Mamat membawa 74 buah jeruk ke pasar. Sampai siang hari, 38 buah jeruk telah laku terjual.",
        question: "Berapa buah jeruk yang belum laku terjual?",
        a: 74,
        b: 38,
        answer: 36,
        objectType: "orange",
        hint: "4 pinjam 1 jadi 14. 14 − 8 = 6. Puluhan 6 − 3 = 3.",
        explanation: "74 jeruk − 38 jeruk = 36 buah jeruk.",
      },
      {
        id: "sp-3",
        title: "Kue Kering di Toko",
        story: "Toko memiliki stok 82 toples kue kering. Menjelang hari raya, 45 toples telah dipesan pelanggan.",
        question: "Berapa toples kue kering yang masih tersisa di toko?",
        a: 82,
        b: 45,
        answer: 37,
        objectType: "cookie",
        hint: "2 pinjam 1 jadi 12. 12 − 5 = 7. Puluhan 7 − 4 = 3.",
        explanation: "82 toples − 45 toples = 37 toples kue kering.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Pengurangan Bersusun Dengan Meminjam",
      instructions: "Jika angka atas lebih kecil dari angka bawah pada kolom satuan, pinjam 1 puluhan (10) dari angka sebelahnya.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "direct",
          question: "Hitung pengurangan bersusun: 54 − 27 = ...",
          a: 54,
          b: 27,
          answer: 27,
          hint: "14 − 7 = 7, 4 − 2 = 2.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "story",
          storyText: "Adik memiliki 65 butir kelereng dan memberikan 28 butir kepada sepupunya.",
          question: "Berapa butir kelereng adik sekarang?",
          a: 65,
          b: 28,
          answer: 37,
          objectType: "marble",
          hint: "15 − 8 = 7, 5 − 2 = 3.",
        },
        {
          id: "ws-3",
          number: 3,
          type: "direct",
          question: "Hitung pengurangan bersusun: 72 − 39 = ...",
          a: 72,
          b: 39,
          answer: 33,
          hint: "12 − 9 = 3, 6 − 3 = 3.",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitung pengurangan 3-digit dengan meminjam: 341 − 168 = ...",
          a: 341,
          b: 168,
          answer: 173,
          hint: "11−8=3, 13−6=7, 2−1=1.",
        },
        {
          id: "ws-5",
          number: 5,
          type: "story",
          storyText: "Perpustakaan memiliki 80 buku cerita dongeng. Sebanyak 34 buku sedang dipinjam siswa.",
          question: "Berapa buku cerita yang masih ada di perpustakaan?",
          a: 80,
          b: 34,
          answer: 46,
          objectType: "book",
          hint: "0 pinjam 1 jadi 10. 10 − 4 = 6. Puluhan 7 − 3 = 4.",
        },
      ],
    },
  },

  // ==========================================
  // PERKALIAN BERSUSUN
  // ==========================================
  {
    id: "mult-column-one-digit",
    operation: "multiplication",
    title: "Perkalian Bersusun (Pengali 1 Digit)",
    subtitle: "Mengalikan satuan kemudian puluhan dengan aturan menyimpan hasil",
    description: "Menyusun bilangan secara vertikal untuk mengalikan bilangan 2 digit dengan 1 digit secara cepat dan teliti.",
    prerequisites: ["mult-facts"],
    representations: ["column-arithmetic", "array"],
    difficulty: 3,
    conceptTitle: "Kalikan Satuan Lalu Puluhan",
    conceptExplanation: "26 × 4: Kalikan 4 dengan satuan 6 terlebih dahulu: 4 × 6 = 24. Tulis 4 di bawah kolom satuan, simpan 2 di atas kolom puluhan. Selanjutnya kalikan 4 dengan puluhan 2: 4 × 2 = 8. Tambahkan simpanan 2: 8 + 2 = 10. Tulis 10 di depan 4. Hasilnya 104.",
    exampleA: 26,
    exampleB: 4,
    strategy: "column-one-digit",
    objectType: "orange",
    mathForm: {
      title: "Perkalian Bersusun Pendek 1 Digit",
      standardExpression: "26 × 4 = 104",
      terms: [
        { term: "26", role: "Bilangan yang Dikalikan", explanation: "2 puluhan dan 6 satuan." },
        { term: "4", role: "Pengali", explanation: "Pengali 1 digit (satuan)." },
        { term: "6 × 4 = 24", role: "Perkalian Satuan", explanation: "Tulis 4 di bawah, simpan 2 di puluhan." },
        { term: "(2 × 4) + 2 = 10", role: "Perkalian Puluhan", explanation: "Kalikan puluhan lalu tambahkan simpanan 2." },
        { term: "104", role: "Hasil Perkalian", explanation: "Total keseluruhan." },
      ],
      note: "Kalikan terlebih dahulu bilangan pengali dengan angka satuan, baru kemudian dengan angka puluhan.",
    },
    guidedPractice: {
      prompt: "Ada 3 kotak pensil. Setiap kotak berisi 24 batang pensil. Berapa total pensil?",
      a: 24,
      b: 3,
      answer: 72,
      hint: "4 × 3 = 12 (tulis 2, simpan 1). (2 × 3) + 1 = 7. Gabungkan: 72.",
      objectType: "pencil",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Tanpa Menyimpan",
        title: "Keranjang Apel: 23 × 3",
        context: "Ada 3 keranjang apel. Setiap keranjang memuat 23 apel. Satuan 3 × 3 = 9, puluhan 2 × 3 = 6.",
        a: 23,
        b: 3,
        objectType: "apple",
        standardExpression: "23 × 3 = 69",
        explanationNote: "Langsung kalikan tanpa simpanan menghasilkan 69 buah apel.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Menyimpan ke Puluhan",
        title: "Jeruk Manis: 26 × 4",
        context: "4 piring masing-masing berisi 26 jeruk. Satuan 6 × 4 = 24 (tulis 4 simpan 2). Puluhan (2 × 4) + 2 = 10.",
        a: 26,
        b: 4,
        objectType: "orange",
        standardExpression: "26 × 4 = 104",
        explanationNote: "Simpanan 2 ditambahkan menghasilkan 104 jeruk.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Angka Berakhiran Nol",
        title: "Kotak Biskuit: 40 × 6",
        context: "6 toples biskuit, masing-masing berisi 40 keping. 0 × 6 = 0, lalu 4 × 6 = 24.",
        a: 40,
        b: 6,
        objectType: "cookie",
        standardExpression: "40 × 6 = 240",
        explanationNote: "Hasilnya 240 keping biskuit.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: 3-Digit × 1-Digit",
        title: "Buku Perpustakaan: 125 × 3",
        context: "3 rak buku masing-masing memuat 125 buku. 5×3=15 (simpan 1), 2×3+1=7, 1×3=3.",
        a: 125,
        b: 3,
        objectType: "book",
        standardExpression: "125 × 3 = 375",
        explanationNote: "Total ada 375 buku.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Dus Pensil Warna",
        story: "Sebuah toko membeli 5 dus pensil warna. Setiap dus berisi 32 pensil warna.",
        question: "Berapa banyak pensil warna yang dibeli toko tersebut?",
        a: 32,
        b: 5,
        answer: 160,
        objectType: "pencil",
        hint: "2 × 5 = 10 (tulis 0 simpan 1). (3 × 5) + 1 = 16.",
        explanation: "5 dus × 32 pensil = 160 batang pensil warna.",
      },
      {
        id: "sp-2",
        title: "Keranjang Jeruk Petani",
        story: "Petani memetik 6 keranjang jeruk manis. Setiap keranjang berisi 25 buah jeruk.",
        question: "Berapa buah jeruk yang dipetik seluruhnya?",
        a: 25,
        b: 6,
        answer: 150,
        objectType: "orange",
        hint: "5 × 6 = 30 (tulis 0 simpan 3). (2 × 6) + 3 = 15.",
        explanation: "6 keranjang × 25 jeruk = 150 buah jeruk.",
      },
      {
        id: "sp-3",
        title: "Paket Buku Donasi",
        story: "Komite sekolah menyiapkan 4 paket kardus buku cerita. Setiap kardus berisi 48 buku cerita anak.",
        question: "Berapa total buku cerita yang ada di keempat kardus?",
        a: 48,
        b: 4,
        answer: 192,
        objectType: "book",
        hint: "8 × 4 = 32 (tulis 2 simpan 3). (4 × 4) + 3 = 19.",
        explanation: "4 kardus × 48 buku = 192 buku cerita.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Perkalian Bersusun (Pengali 1 Digit)",
      instructions: "Kalikan pengali dengan angka satuan terlebih dahulu, simpan bila ada, lalu kalikan dengan puluhan.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "direct",
          question: "Hitung perkalian bersusun: 34 × 2 = ...",
          a: 34,
          b: 2,
          answer: 68,
          hint: "4 × 2 = 8, 3 × 2 = 6.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "story",
          storyText: "Ibu membeli 3 kantong apel merah. Setiap kantong berisi 28 buah apel.",
          question: "Berapa butir apel yang dibeli ibu seluruhnya?",
          a: 28,
          b: 3,
          answer: 84,
          objectType: "apple",
          hint: "8 × 3 = 24 (simpan 2). 2 × 3 + 2 = 8.",
        },
        {
          id: "ws-3",
          number: 3,
          type: "direct",
          question: "Hitung perkalian bersusun: 45 × 4 = ...",
          a: 45,
          b: 4,
          answer: 180,
          hint: "5 × 4 = 20 (simpan 2). 4 × 4 + 2 = 18.",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitung perkalian 3-digit: 115 × 5 = ...",
          a: 115,
          b: 5,
          answer: 575,
          hint: "5×5=25 (simpan 2). 1×5+2=7. 1×5=5.",
        },
        {
          id: "ws-5",
          number: 5,
          type: "story",
          storyText: "Di toko ada 6 toples kue kering. Tiap toples memuat 35 butir kue nastar.",
          question: "Berapa banyak kue nastar seluruhnya?",
          a: 35,
          b: 6,
          answer: 210,
          objectType: "cookie",
          hint: "5 × 6 = 30 (simpan 3). 3 × 6 + 3 = 21.",
        },
      ],
    },
  },

  {
    id: "mult-column-two-digit",
    operation: "multiplication",
    title: "Perkalian Bersusun (Pengali 2 Digit)",
    subtitle: "Perkalian bersusun pendek 2 tingkat: baris satuan, baris puluhan, lalu jumlahkan",
    description: "Mengalikan bilangan dua digit dengan dua digit menggunakan dua baris hasil kali parsial yang digeser satu digit sebelum dijumlahkan.",
    prerequisites: ["mult-column-one-digit"],
    representations: ["column-arithmetic", "array"],
    difficulty: 4,
    conceptTitle: "Dua Tingkat Baris Perkalian",
    conceptExplanation: "34 × 26: Baris 1: kalikan 34 dengan satuan 6 = 204. Baris 2: kalikan 34 dengan puluhan 2 = 68 (ditulis maju 1 kolom ke kiri karena bernilai 680). Terakhir buat garis tambah: 204 + 680 = 884.",
    exampleA: 34,
    exampleB: 26,
    strategy: "column-two-digit",
    objectType: "book",
    mathForm: {
      title: "Perkalian Bersusun Pendek 2 Tingkat",
      standardExpression: "34 × 26 = 884",
      terms: [
        { term: "34 × 6 = 204", role: "Baris 1 (Hasil Kali Satuan)", explanation: "Kalikan 34 dengan angka satuan 6." },
        { term: "34 × 20 = 680", role: "Baris 2 (Hasil Kali Puluhan)", explanation: "Kalikan 34 dengan angka puluhan 2 (geser 1 kolom)." },
        { term: "204 + 680 = 884", role: "Penjumlahan Kedua Baris", explanation: "Jumlahkan baris 1 dan baris 2 untuk mendapatkan hasil akhir." },
      ],
      note: "Baris kedua harus selalu digeser satu kolom ke kiri karena pengalinya adalah nilai tempat puluhan.",
    },
    guidedPractice: {
      prompt: "Hitunglah 25 × 14 dengan perkalian bersusun dua tingkat.",
      a: 25,
      b: 14,
      answer: 350,
      hint: "Baris 1: 25 × 4 = 100. Baris 2: 25 × 1 = 25 (geser 1 angka = 250). Jumlahkan: 100 + 250 = 350.",
      objectType: "book",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Puluhan × Belasan Kecil",
        title: "Dus Buku Cerita: 24 × 12",
        context: "Baris 1: 24 × 2 = 48. Baris 2: 24 × 1 = 24 (geser 1 angka). Jumlahkan: 48 + 240 = 288.",
        a: 24,
        b: 12,
        objectType: "book",
        standardExpression: "24 × 12 = 288",
        explanationNote: "Total ada 288 buku cerita.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Puluhan × Puluhan Besar",
        title: "Pensil Koperasi: 34 × 26",
        context: "Baris 1: 34 × 6 = 204. Baris 2: 34 × 2 = 68 (geser 1 angka). Jumlahkan: 204 + 680 = 884.",
        a: 34,
        b: 26,
        objectType: "pencil",
        standardExpression: "34 × 26 = 884",
        explanationNote: "Total 884 batang pensil.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Pengali Berakhiran Nol",
        title: "Karton Telur: 45 × 20",
        context: "Karena pengali berakhiran 0, cukup kalikan 45 × 2 = 90 lalu tambahkan angka 0 di belakangnya = 900.",
        a: 45,
        b: 20,
        objectType: "egg",
        standardExpression: "45 × 20 = 900",
        explanationNote: "Total 900 butir telur.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Bilangan Kembar",
        title: "Biskuit Kemasan: 25 × 25",
        context: "Baris 1: 25 × 5 = 125. Baris 2: 25 × 2 = 50 (geser 1 angka). 125 + 500 = 625.",
        a: 25,
        b: 25,
        objectType: "cookie",
        standardExpression: "25 × 25 = 625",
        explanationNote: "Total 625 keping biskuit.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Pesanan Biskuit Bazar",
        story: "Panitia bazar memesan 15 kardus biskuit. Setiap kardus berisi 24 bungkus biskuit cokelat.",
        question: "Berapa bungkus biskuit cokelat yang dipesan seluruhnya?",
        a: 24,
        b: 15,
        answer: 360,
        objectType: "cookie",
        hint: "Baris 1: 24 × 5 = 120. Baris 2: 24 × 1 = 24 (240). 120 + 240 = 360.",
        explanation: "15 kardus × 24 bungkus = 360 bungkus biskuit.",
      },
      {
        id: "sp-2",
        title: "Kiriman Buku Paket",
        story: "Perpustakaan kota mengirim 18 paket buku ke sekolah dasar. Tiap paket berisi 35 buku pelajaran.",
        question: "Berapa total buku pelajaran yang dikirim perpustakaan kota?",
        a: 35,
        b: 18,
        answer: 630,
        objectType: "book",
        hint: "Baris 1: 35 × 8 = 280. Baris 2: 35 × 1 = 35 (350). 280 + 350 = 630.",
        explanation: "18 paket × 35 buku = 630 buku pelajaran.",
      },
      {
        id: "sp-3",
        title: "Peti Buah Jeruk",
        story: "Koperasi membeli 22 peti buah jeruk. Setiap peti memuat 42 buah jeruk manis segar.",
        question: "Berapa jumlah butir jeruk yang dibeli koperasi?",
        a: 42,
        b: 22,
        answer: 924,
        objectType: "orange",
        hint: "Baris 1: 42 × 2 = 84. Baris 2: 42 × 2 = 84 (840). 84 + 840 = 924.",
        explanation: "22 peti × 42 jeruk = 924 butir jeruk.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Perkalian Bersusun (Pengali 2 Digit)",
      instructions: "Hitung perkalian bersusun dua tingkat. Luruskan baris kedua maju 1 kolom ke kiri sebelum dijumlahkan.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "direct",
          question: "Hitung perkalian bersusun: 23 × 15 = ...",
          a: 23,
          b: 15,
          answer: 345,
          hint: "Baris 1: 23 × 5 = 115. Baris 2: 23 × 1 = 23 (230). 115 + 230 = 345.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "story",
          storyText: "Ada 16 kotak pensil. Setiap kotak berisi 24 pensil.",
          question: "Berapa banyak pensil seluruhnya?",
          a: 24,
          b: 16,
          answer: 384,
          objectType: "pencil",
          hint: "24 × 6 = 144, 24 × 1 = 24 (240). 144 + 240 = 384.",
        },
        {
          id: "ws-3",
          number: 3,
          type: "direct",
          question: "Hitung perkalian bersusun: 32 × 24 = ...",
          a: 32,
          b: 24,
          answer: 768,
          hint: "32 × 4 = 128, 32 × 2 = 64 (640). 128 + 640 = 768.",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitung perkalian dengan angka puluhan genap: 48 × 20 = ...",
          a: 48,
          b: 20,
          answer: 960,
          hint: "48 × 2 = 96, tambahkan 0 -> 960.",
        },
        {
          id: "ws-5",
          number: 5,
          type: "story",
          storyText: "Di gudang terdapat 25 kardus telur. Setiap kardus berisi 36 butir telur.",
          question: "Berapa butir telur yang ada di gudang?",
          a: 36,
          b: 25,
          answer: 900,
          objectType: "egg",
          hint: "36 × 5 = 180, 36 × 2 = 72 (720). 180 + 720 = 900.",
        },
      ],
    },
  },

  // ==========================================
  // PEMBAGIAN BERSUSUN (POROGAPIT)
  // ==========================================
  {
    id: "div-porogapit-exact",
    operation: "division",
    title: "Pembagian Bersusun (Porogapit Tanpa Sisa)",
    subtitle: "Metode Ba-Ka-Kur-Tu (Bagi, Kali, Kurang, Turunkan) sampai sisa 0",
    description: "Cara membagi bilangan puluhan atau ratusan dengan porogapit mengikuti empat langkah berulang yang mudah diingat.",
    prerequisites: ["div-fact-families"],
    representations: ["porogapit", "equal-groups"],
    difficulty: 3,
    conceptTitle: "Langkah Porogapit: Ba - Ka - Kur - Tu",
    conceptExplanation: "72 ÷ 3: 1) Bagi: 7 ÷ 3 = 2 (tulis 2 di atas). 2) Kali: 2 × 3 = 6 (tulis di bawah 7). 3) Kurang: 7 − 6 = 1. 4) Turunkan angka 2 di sebelah 1 menjadi 12. Ulangi: 12 ÷ 3 = 4 (tulis di atas), 4 × 3 = 12, 12 − 12 = 0. Sisa 0, hasil akhirnya 24.",
    exampleA: 72,
    exampleB: 3,
    strategy: "porogapit",
    objectType: "orange",
    mathForm: {
      title: "Bagan Porogapit Ba-Ka-Kur-Tu",
      standardExpression: "72 ÷ 3 = 24",
      terms: [
        { term: "72", role: "Yang Dibagi", explanation: "Bilangan di dalam kurung porogapit." },
        { term: "3", role: "Pembagi", explanation: "Bilangan di sebelah kiri kurung porogapit." },
        { term: "24", role: "Hasil Bagi", explanation: "Bilangan di atas garis porogapit." },
        { term: "0", role: "Sisa Pembagian", explanation: "Sisa akhir pembagian tanpa sisa (habis dibagi)." },
      ],
      note: "Hafalkan jembatan ingatan: Ba (Bagi) -> Ka (Kali) -> Kur (Kurang) -> Tu (Turunkan).",
    },
    guidedPractice: {
      prompt: "Hitunglah 84 ÷ 4 dengan porogapit.",
      a: 84,
      b: 4,
      answer: 21,
      hint: "Bagi: 8 ÷ 4 = 2 (kali 8, kurang 0, turun 4). Bagi: 4 ÷ 4 = 1. Hasil: 21.",
      objectType: "orange",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Puluhan Habis Dibagi",
        title: "Jeruk Manis: 72 ÷ 3",
        context: "72 buah jeruk dibagikan rata ke 3 keranjang. Siklus 1: 7 ÷ 3 = 2 (sisa 1, turun 2 -> 12). Siklus 2: 12 ÷ 3 = 4 (sisa 0).",
        a: 72,
        b: 3,
        objectType: "orange",
        standardExpression: "72 ÷ 3 = 24",
        explanationNote: "Setiap keranjang mendapatkan 24 buah jeruk.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Puluhan Besar",
        title: "Apel Segar: 96 ÷ 4",
        context: "96 apel dibagi ke 4 dus. 9 ÷ 4 = 2 (kali 8, sisa 1, turun 6 -> 16). 16 ÷ 4 = 4. Hasilnya 24.",
        a: 96,
        b: 4,
        objectType: "apple",
        standardExpression: "96 ÷ 4 = 24",
        explanationNote: "Tiap dus berisi 24 buah apel.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: 3-Digit Ambil 2 Angka Depan",
        title: "Pensil Ujian: 156 ÷ 4",
        context: "Karena angka pertama 1 < 4, ambil 2 angka pertama: 15 ÷ 4 = 3 (kali 12, sisa 3, turun 6 -> 36). 36 ÷ 4 = 9.",
        a: 156,
        b: 4,
        objectType: "pencil",
        standardExpression: "156 ÷ 4 = 39",
        explanationNote: "Hasil baginya adalah 39 batang pensil.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Hasil Ada Angka Nol di Tengah",
        title: "Buku Perpustakaan: 525 ÷ 5",
        context: "5 ÷ 5 = 1. Turun 2: 2 ÷ 5 = 0 (tulis 0 di atas!). Turun 5: 25 ÷ 5 = 5. Hasilnya 105.",
        a: 525,
        b: 5,
        objectType: "book",
        standardExpression: "525 ÷ 5 = 105",
        explanationNote: "Penting: saat angka turun lebih kecil dari pembagi, tulis angka 0 pada hasil bagi!",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Membagi Kelereng Rata",
        story: "Deni memiliki 78 butir kelereng yang ingin dibagikan sama banyak kepada 3 orang temannya.",
        question: "Berapa butir kelereng yang diterima setiap teman Deni?",
        a: 78,
        b: 3,
        answer: 26,
        objectType: "marble",
        hint: "7 ÷ 3 = 2 (sisa 1, turun 8 -> 18). 18 ÷ 3 = 6.",
        explanation: "78 kelereng ÷ 3 orang = 26 butir kelereng tiap orang.",
      },
      {
        id: "sp-2",
        title: "Kemasan Biskuit Cokelat",
        story: "Pabrik kue memiliki 92 keping biskuit yang akan dikemas ke dalam 4 kotak kaleng sama banyak.",
        question: "Berapa butir biskuit pada setiap kotak kaleng?",
        a: 92,
        b: 4,
        answer: 23,
        objectType: "cookie",
        hint: "9 ÷ 4 = 2 (sisa 1, turun 2 -> 12). 12 ÷ 4 = 3.",
        explanation: "92 biskuit ÷ 4 kotak = 23 keping biskuit per kotak.",
      },
      {
        id: "sp-3",
        title: "Paket Buku Donasi",
        story: "Ada 168 buku bacaan yang dibagikan merata ke 6 sekolah dasar di daerah binaan.",
        question: "Berapa banyak buku yang diperoleh masing-masing sekolah?",
        a: 168,
        b: 6,
        answer: 28,
        objectType: "book",
        hint: "16 ÷ 6 = 2 (sisa 4, turun 8 -> 48). 48 ÷ 6 = 8.",
        explanation: "168 buku ÷ 6 sekolah = 28 buku tiap sekolah.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Pembagian Bersusun (Porogapit Tanpa Sisa)",
      instructions: "Gunakan cara porogapit langkah demi langkah: Bagi, Kali, Kurang, lalu Turunkan hingga sisanya 0.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "direct",
          question: "Hitung porogapit: 68 ÷ 2 = ...",
          a: 68,
          b: 2,
          answer: 34,
          hint: "6 ÷ 2 = 3, 8 ÷ 2 = 4.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "story",
          storyText: "Paman memanen 96 buah mangga dan memasukkannya ke dalam 3 keranjang sama banyak.",
          question: "Berapa butir mangga isi setiap keranjang?",
          a: 96,
          b: 3,
          answer: 32,
          objectType: "orange",
          hint: "9 ÷ 3 = 3, 6 ÷ 3 = 2.",
        },
        {
          id: "ws-3",
          number: 3,
          type: "direct",
          question: "Hitung porogapit: 84 ÷ 3 = ...",
          a: 84,
          b: 3,
          answer: 28,
          hint: "8 ÷ 3 = 2 (sisa 2, turun 4 -> 24). 24 ÷ 3 = 8.",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitung porogapit 3-digit: 144 ÷ 4 = ...",
          a: 144,
          b: 4,
          answer: 36,
          hint: "14 ÷ 4 = 3 (sisa 2, turun 4 -> 24). 24 ÷ 4 = 6.",
        },
        {
          id: "ws-5",
          number: 5,
          type: "story",
          storyText: "Sebanyak 135 butir telur dimasukkan ke dalam 5 rak karton secara merata.",
          question: "Berapa butir telur pada setiap rak?",
          a: 135,
          b: 5,
          answer: 27,
          objectType: "egg",
          hint: "13 ÷ 5 = 2 (sisa 3, turun 5 -> 35). 35 ÷ 5 = 7.",
        },
      ],
    },
  },

  {
    id: "div-porogapit-remainder",
    operation: "division",
    title: "Pembagian Bersusun (Porogapit Dengan Sisa)",
    subtitle: "Menemukan hasil bagi dan sisa pembagian pada tahap akhir",
    description: "Ketika bilangan tidak habis dibagi rata, pembagian porogapit menghasilkan nilai sisa yang lebih kecil dari pembagi.",
    prerequisites: ["div-porogapit-exact"],
    representations: ["porogapit", "equal-groups"],
    difficulty: 4,
    conceptTitle: "Mengenal Sisa Pembagian",
    conceptExplanation: "75 ÷ 4: 1) 7 ÷ 4 = 1, 1 × 4 = 4, 7 − 4 = 3. 2) Turunkan 5 menjadi 35. 3) 35 ÷ 4 = 8, 8 × 4 = 32, 35 − 32 = 3. Tidak ada angka lagi yang bisa diturunkan. Maka hasil baginya adalah 18 dengan sisa 3.",
    exampleA: 75,
    exampleB: 4,
    strategy: "porogapit-remainder",
    objectType: "cookie",
    mathForm: {
      title: "Bagan Porogapit dengan Nilai Sisa",
      standardExpression: "75 ÷ 4 = 18 (sisa 3)",
      terms: [
        { term: "75", role: "Yang Dibagi", explanation: "Bilangan asal yang dibagi." },
        { term: "4", role: "Pembagi", explanation: "Bilangan pembagi kelompok." },
        { term: "18", role: "Hasil Bagi", explanation: "Banyaknya isi utuh tiap kelompok." },
        { term: "3", role: "Sisa Akhir", explanation: "Benda sisa yang tidak cukup dibagikan lagi (3 < 4)." },
      ],
      note: "Sisa pembagian harus selalu lebih kecil dari pembagi.",
    },
    guidedPractice: {
      prompt: "Berapa hasil bagi dari 53 ÷ 5? (Tuliskan nilai hasil baginya saja)",
      a: 53,
      b: 5,
      answer: 10,
      hint: "5 ÷ 5 = 1. Turunkan 3: 3 ÷ 5 = 0. Jadi hasil bagi = 10, sisa 3.",
      objectType: "cookie",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Sisa Kecil",
        title: "Kue Pesta: 75 ÷ 4",
        context: "75 kue dibagi ke 4 piring. Masing-masing piring berisi 18 kue, tersisa 3 kue di luar piring.",
        a: 75,
        b: 4,
        objectType: "cookie",
        standardExpression: "75 ÷ 4 = 18 (sisa 3)",
        explanationNote: "Hasil bagi 18, sisa 3.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Sisa 1",
        title: "Kelereng Kantong: 85 ÷ 6",
        context: "85 kelereng dibagi ke 6 kantong. 8 ÷ 6 = 1 (sisa 2, turun 5 -> 25). 25 ÷ 6 = 4 (kali 24, sisa 1).",
        a: 85,
        b: 6,
        objectType: "marble",
        standardExpression: "85 ÷ 6 = 14 (sisa 1)",
        explanationNote: "Tiap kantong berisi 14 kelereng, tersisa 1 kelereng.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: 3-Digit Dengan Sisa",
        title: "Telur Ayam Peternak: 245 ÷ 6",
        context: "24 ÷ 6 = 4 (sisa 0). Turun 5: 5 ÷ 6 = 0 (tulis 0 di atas). Sisa 5.",
        a: 245,
        b: 6,
        objectType: "egg",
        standardExpression: "245 ÷ 6 = 40 (sisa 5)",
        explanationNote: "Hasil bagi 40 dengan sisa 5 butir telur.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Pembagian Jeruk",
        title: "Jeruk Manis: 95 ÷ 7",
        context: "9 ÷ 7 = 1 (sisa 2, turun 5 -> 25). 25 ÷ 7 = 3 (kali 21, sisa 4).",
        a: 95,
        b: 7,
        objectType: "orange",
        standardExpression: "95 ÷ 7 = 13 (sisa 4)",
        explanationNote: "Hasil bagi 13 dengan sisa 4 buah jeruk.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Membungkus Permen",
        story: "Ibu memiliki 67 butir permen cokelat dan ingin membungkusnya ke dalam 5 kantong plastik sama banyak.",
        question: "Berapa butir permen pada setiap kantong? (Tulis hasil baginya)",
        a: 67,
        b: 5,
        answer: 13,
        objectType: "cookie",
        hint: "67 ÷ 5 = 13 dengan sisa 2 butir permen.",
        explanation: "Setiap kantong berisi 13 permen dan tersisa 2 permen.",
      },
      {
        id: "sp-2",
        title: "Kardus Jeruk",
        story: "Paman membawa 86 buah jeruk untuk dimasukkan ke dalam 4 kardus sama banyak.",
        question: "Berapa banyak jeruk di setiap kardus? (Tulis hasil baginya)",
        a: 86,
        b: 4,
        answer: 21,
        objectType: "orange",
        hint: "86 ÷ 4 = 21 sisa 2.",
        explanation: "Tiap kardus memuat 21 jeruk dan tersisa 2 buah jeruk.",
      },
      {
        id: "sp-3",
        title: "Kemasan Telur Ayam",
        story: "Peternak mengemas 98 butir telur ke dalam wadah yang masing-masing muat 8 butir telur.",
        question: "Berapa wadah penuh yang dihasilkan peternak?",
        a: 98,
        b: 8,
        answer: 12,
        objectType: "egg",
        hint: "98 ÷ 8 = 12 sisa 2.",
        explanation: "Dihasilkan 12 wadah penuh telur dan tersisa 2 butir telur.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Porogapit Dengan Sisa",
      instructions: "Hitunglah pembagian porogapit berikut, lalu tuliskan nilai hasil baginya.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "direct",
          question: "Hitung hasil bagi dari 47 ÷ 4 = ... (tulis nilai hasil baginya)",
          a: 47,
          b: 4,
          answer: 11,
          hint: "47 ÷ 4 = 11 sisa 3.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "story",
          storyText: "Ada 58 buku cerita yang dibagi ke 5 kelompok belajar sama banyak.",
          question: "Berapa buku yang diterima tiap kelompok?",
          a: 58,
          b: 5,
          answer: 11,
          objectType: "book",
          hint: "58 ÷ 5 = 11 sisa 3 buku.",
        },
        {
          id: "ws-3",
          number: 3,
          type: "direct",
          question: "Hitung hasil bagi dari 83 ÷ 6 = ...",
          a: 83,
          b: 6,
          answer: 13,
          hint: "83 ÷ 6 = 13 sisa 5.",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitung hasil bagi dari 95 ÷ 8 = ...",
          a: 95,
          b: 8,
          answer: 11,
          hint: "95 ÷ 8 = 11 sisa 7.",
        },
        {
          id: "ws-5",
          number: 5,
          type: "story",
          storyText: "Sebanyak 74 butir kelereng dimasukkan ke dalam 6 kantong secara sama rata.",
          question: "Berapa isi kelereng dalam setiap kantong?",
          a: 74,
          b: 6,
          answer: 12,
          objectType: "marble",
          hint: "74 ÷ 6 = 12 sisa 2 butir kelereng.",
        },
      ],
    },
  },
];
