import { Operation } from "@math-sd/math-engine";
import { COLUMN_SKILLS } from "./columnSkills";

export { COLUMN_SKILLS } from "./columnSkills";

export type MathFormTerm = {
  term: string;
  role: string;
  explanation: string;
};

export type MathForm = {
  title: string;
  repeatedExpression?: string;
  standardExpression: string;
  terms: MathFormTerm[];
  note?: string;
};

export type SkillObjectType =
  | "apple"
  | "orange"
  | "motorcycle"
  | "pencil"
  | "egg"
  | "cookie"
  | "book"
  | "marble"
  | "car"
  | "dot";

export type SkillExample = {
  id: string;
  badge: string;
  title: string;
  context: string;
  a: number;
  b: number;
  strategy?: string;
  objectType?: SkillObjectType;
  secondObjectType?: SkillObjectType;
  color?: string;
  secondColor?: string;
  repeatedExpression?: string;
  standardExpression: string;
  explanationNote?: string;
};

export type StoryProblem = {
  id: string;
  title: string;
  story: string;
  question: string;
  a: number;
  b: number;
  answer: number;
  objectType: SkillObjectType;
  secondObjectType?: SkillObjectType;
  color?: string;
  secondColor?: string;
  hint: string;
  explanation: string;
};

export type WorksheetItem = {
  id: string;
  number: number;
  type: "story" | "direct" | "visual";
  storyText?: string;
  question: string;
  a?: number;
  b?: number;
  answer: number;
  objectType?: SkillObjectType;
  secondObjectType?: SkillObjectType;
  color?: string;
  secondColor?: string;
  unit?: string;
  hint?: string;
};

export type Worksheet = {
  title: string;
  instructions: string;
  items: WorksheetItem[];
};

export type Skill = {
  id: string;
  operation: Operation;
  title: string;
  subtitle: string;
  description: string;
  prerequisites: string[];
  representations: string[];
  difficulty: 1 | 2 | 3 | 4 | 5;
  conceptTitle: string;
  conceptExplanation: string;
  exampleA: number;
  exampleB: number;
  strategy: string;
  objectType?: SkillObjectType;
  mathForm?: MathForm;
  examples?: SkillExample[];
  storyProblems?: StoryProblem[];
  worksheet?: Worksheet;
  guidedPractice: {
    prompt: string;
    a: number;
    b: number;
    answer: number;
    hint: string;
    objectType?: SkillObjectType;
    secondObjectType?: SkillObjectType;
    color?: string;
    secondColor?: string;
  };
};

export const INITIAL_SKILLS: Skill[] = [
  // --- PERKALIAN (Vertical Slice Utama) ---
  {
    id: "mult-equal-groups",
    operation: "multiplication",
    title: "Kelompok yang Sama",
    subtitle: "Makna dasar perkalian sebagai kelompok berulang",
    description: "Memahami perkalian sebagai penjumlahan berulang dari kelompok-kelompok yang berisi benda sama banyak.",
    prerequisites: ["add-up-to-10"],
    representations: ["equal-groups", "counters"],
    difficulty: 1,
    conceptTitle: "4 Piring Berisi Jeruk",
    conceptExplanation: "Ketika kita memiliki 4 piring dan setiap piring berisi 3 buah jeruk segar, kita menggunakan perkalian: 4 piring × 3 jeruk = 12 jeruk.",
    exampleA: 4,
    exampleB: 3,
    strategy: "equal-groups",
    objectType: "orange",
    mathForm: {
      title: "Dari Gambar Jeruk ke Bentuk Matematika",
      repeatedExpression: "3 + 3 + 3 + 3 = 12",
      standardExpression: "4 × 3 = 12",
      terms: [
        { term: "4", role: "Banyak Piring (Kelompok)", explanation: "Ada 4 piring wadah." },
        { term: "×", role: "Tanda Kali", explanation: "Menandakan pengelompokan yang berulang." },
        { term: "3", role: "Isi Jeruk Tiap Piring", explanation: "Setiap piring berisi 3 buah jeruk." },
        { term: "=", role: "Sama Dengan", explanation: "Menunjukkan total yang setara." },
        { term: "12", role: "Total Jeruk", explanation: "Total seluruh 12 buah jeruk." },
      ],
      note: "Urutan konseptual: (Banyak Kelompok) × (Isi Tiap Kelompok). 4 kelompok berisi 3 benda ditulis 4 × 3 = 12.",
    },
    guidedPractice: {
      prompt: "Ada 3 wadah apel. Setiap wadah berisi 4 buah apel merah. Berapa jumlah seluruh apel?",
      a: 3,
      b: 4,
      answer: 12,
      hint: "Bayangkan 3 wadah, masing-masing berisi 4 apel: 4 + 4 + 4 = ?",
      objectType: "apple",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Kelompok Sedikit",
        title: "2 Piring Apel",
        context: "Ada 2 piring di meja. Setiap piring berisi 3 buah apel merah segar.",
        a: 2,
        b: 3,
        objectType: "apple",
        repeatedExpression: "3 + 3 = 6",
        standardExpression: "2 × 3 = 6",
        explanationNote: "Kelompok sedikit mudah dihitung langsung untuk memahami konsep awal.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Kelompok Sedang",
        title: "4 Piring Jeruk",
        context: "Ketika kita memiliki 4 piring dan setiap piring berisi 3 buah jeruk manis segar.",
        a: 4,
        b: 3,
        objectType: "orange",
        repeatedExpression: "3 + 3 + 3 + 3 = 12",
        standardExpression: "4 × 3 = 12",
        explanationNote: "Penjumlahan berulang dari 4 kelompok yang masing-masing berisi 3 benda.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Dikalikan 1",
        title: "5 Piring Berisi 1 Kue",
        context: "Ada 5 piring di meja pesta. Setiap piring memuat 1 potong kue cokelat.",
        a: 5,
        b: 1,
        objectType: "cookie",
        repeatedExpression: "1 + 1 + 1 + 1 + 1 = 5",
        standardExpression: "5 × 1 = 5",
        explanationNote: "Setiap bilangan yang dikalikan 1 menghasilkan bilangan itu sendiri.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Kelompok Isi Banyak",
        title: "3 Kotak Pensil Warna",
        context: "Ibu membeli 3 kotak pensil warna untuk adik. Setiap kotak berisi 5 pensil.",
        a: 3,
        b: 5,
        objectType: "pencil",
        repeatedExpression: "5 + 5 + 5 = 15",
        standardExpression: "3 × 5 = 15",
        explanationNote: "Menghitung loncatan 5 sebanyak 3 kali (5, 10, 15).",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Keranjang Jeruk Nenek",
        story: "Nenek membawa 3 keranjang belanja dari pasar. Setiap keranjang berisi 4 buah jeruk manis segar.",
        question: "Berapa buah jeruk yang dibawa nenek seluruhnya?",
        a: 3,
        b: 4,
        answer: 12,
        objectType: "orange",
        hint: "Ada 3 keranjang, masing-masing berisi 4 jeruk: 4 + 4 + 4 = ?",
        explanation: "3 keranjang × 4 jeruk = 12 buah jeruk.",
      },
      {
        id: "sp-2",
        title: "Nampan Kue Cokelat",
        story: "Kakak memanggang kue di dapur dan menaruhnya pada 4 nampan. Setiap nampan memuat 2 potong kue cokelat lezat.",
        question: "Berapa banyak kue cokelat yang dipanggang kakak?",
        a: 4,
        b: 2,
        answer: 8,
        objectType: "cookie",
        hint: "Ada 4 nampan, masing-masing berisi 2 kue: 2 + 2 + 2 + 2 = ?",
        explanation: "4 nampan × 2 kue = 8 potong kue.",
      },
      {
        id: "sp-3",
        title: "Paket Buku Cerita",
        story: "Perpustakaan mengemas buku cerita ke dalam 5 paket kardus. Setiap paket berisi 3 buku cerita bergambar.",
        question: "Berapa total buku cerita yang dikemas perpustakaan?",
        a: 5,
        b: 3,
        answer: 15,
        objectType: "book",
        hint: "Ada 5 paket × 3 buku tiap paket: 3 + 3 + 3 + 3 + 3 = ?",
        explanation: "5 paket × 3 buku = 15 buku cerita.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Konsep Perkalian Kelompok Sama",
      instructions: "Amati gambar objek nyata atau baca soal dengan teliti, lalu tuliskan jawaban yang tepat pada kotak yang disediakan.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "visual",
          storyText: "Ada 3 piring di meja makan. Setiap piring berisi 4 buah apel merah.",
          question: "Berapa jumlah seluruh apel di atas meja?",
          a: 3,
          b: 4,
          answer: 12,
          objectType: "apple",
          unit: "apel",
          hint: "3 piring × 4 apel = ?",
        },
        {
          id: "ws-2",
          number: 2,
          type: "visual",
          storyText: "Budi memiliki 4 bungkus kue biskuit. Setiap bungkus berisi 3 keping biskuit lezat.",
          question: "Berapa jumlah biskuit yang dimiliki Budi?",
          a: 4,
          b: 3,
          answer: 12,
          objectType: "cookie",
          unit: "kue",
          hint: "4 bungkus × 3 biskuit = ?",
        },
        {
          id: "ws-3",
          number: 3,
          type: "story",
          storyText: "Di kelas terdapat 2 meja belajar. Di setiap meja ada 5 batang pensil warna.",
          question: "Berapa banyak pensil warna di kedua meja tersebut?",
          a: 2,
          b: 5,
          answer: 10,
          objectType: "pencil",
          unit: "pensil",
          hint: "2 meja × 5 pensil = ?",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitunglah hasil perkalian langsung berikut: 5 × 2 = ...",
          a: 5,
          b: 2,
          answer: 10,
          hint: "Penjumlahan 2 sebanyak 5 kali: 2 + 2 + 2 + 2 + 2",
        },
        {
          id: "ws-5",
          number: 5,
          type: "direct",
          question: "Hitunglah hasil perkalian langsung berikut: 4 × 4 = ...",
          a: 4,
          b: 4,
          answer: 16,
          hint: "4 kelompok berisi 4: 4 + 4 + 4 + 4",
        },
      ],
    },
  },
  {
    id: "mult-arrays",
    operation: "multiplication",
    title: "Susunan Baris dan Kolom (Array)",
    subtitle: "Melihat perkalian dalam bentuk kisi teratur",
    description: "Memahami perkalian melalui baris dan kolom yang rapi untuk melihat sifat komutatif (a × b = b × a).",
    prerequisites: ["mult-equal-groups"],
    representations: ["array"],
    difficulty: 2,
    conceptTitle: "Tempat Parkir: 3 Baris Motor",
    conceptExplanation: "Di tempat parkir terdapat 3 baris motor yang rapi. Setiap baris memuat 4 motor. Total motor adalah 3 baris × 4 motor = 12 motor.",
    exampleA: 3,
    exampleB: 4,
    strategy: "array",
    objectType: "motorcycle",
    mathForm: {
      title: "Dari Kisi Baris & Kolom ke Bentuk Perkalian",
      repeatedExpression: "4 + 4 + 4 = 12",
      standardExpression: "3 × 4 = 12",
      terms: [
        { term: "3", role: "Banyak Baris", explanation: "Ada 3 baris motor dari atas ke bawah." },
        { term: "×", role: "Tanda Kali", explanation: "Menandakan perkalian kisi baris dan kolom." },
        { term: "4", role: "Banyak Kolom (Isi Tiap Baris)", explanation: "Ada 4 motor di setiap baris ke samping." },
        { term: "=", role: "Sama Dengan", explanation: "Menunjukkan jumlah total benda." },
        { term: "12", role: "Total Objek", explanation: "3 baris × 4 kolom = 12 sepeda motor." },
      ],
      note: "Baris × Kolom = Total Objek. Jika dibalik (4 × 3), hasilnya tetap 12.",
    },
    guidedPractice: {
      prompt: "Sebuah rak buku memiliki 2 baris. Setiap baris memuat 6 buku. Berapa total buku?",
      a: 2,
      b: 6,
      answer: 12,
      hint: "Hitung 2 baris × 6 kolom buku = ?",
      objectType: "book",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Baris Motor",
        title: "Tempat Parkir: 3 Baris Motor",
        context: "Di tempat parkir terdapat 3 baris motor yang rapi. Setiap baris memuat 4 motor.",
        a: 3,
        b: 4,
        objectType: "motorcycle",
        repeatedExpression: "4 + 4 + 4 = 12",
        standardExpression: "3 × 4 = 12",
        explanationNote: "3 baris × 4 kolom = 12 sepeda motor.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Rak Buku",
        title: "Rak Perpustakaan: 2 Baris Buku",
        context: "Sebuah rak buku memiliki 2 baris susunan. Setiap baris memuat 6 buku ensiklopedia.",
        a: 2,
        b: 6,
        objectType: "book",
        repeatedExpression: "6 + 6 = 12",
        standardExpression: "2 × 6 = 12",
        explanationNote: "2 baris × 6 kolom = 12 buku.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Garasi Mobil",
        title: "Garasi Toko: 4 Baris Mobil",
        context: "Toko mobil memajang armadanya dalam 4 baris. Setiap baris berisi 2 mobil.",
        a: 4,
        b: 2,
        objectType: "car",
        repeatedExpression: "2 + 2 + 2 + 2 = 8",
        standardExpression: "4 × 2 = 8",
        explanationNote: "4 baris × 2 kolom = 8 mobil.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Sifat Komutatif",
        title: "Membalik Baris & Kolom (4×3 = 3×4)",
        context: "Susunan 4 baris motor dengan 3 kolom sama hasilnya dengan 3 baris motor berisi 4 kolom.",
        a: 4,
        b: 3,
        objectType: "motorcycle",
        repeatedExpression: "3 + 3 + 3 + 3 = 12",
        standardExpression: "4 × 3 = 12",
        explanationNote: "Sifat komutatif perkalian: urutan dibalik hasilnya tetap sama.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Parkiran Motor Sekolah",
        story: "Di halaman sekolah, satpam menata motor dalam 3 baris rapi. Di setiap baris terdapat 5 sepeda motor.",
        question: "Berapa banyak sepeda motor yang terparkir seluruhnya?",
        a: 3,
        b: 5,
        answer: 15,
        objectType: "motorcycle",
        hint: "3 baris × 5 kolom motor: 5 + 5 + 5 = ?",
        explanation: "3 baris × 5 motor = 15 sepeda motor.",
      },
      {
        id: "sp-2",
        title: "Pajangan Buku Cerita",
        story: "Di etalase toko buku, buku anak ditata dalam 4 baris. Di setiap baris terdapat 3 buku cerita.",
        question: "Berapa total buku cerita yang dipajang di etalase?",
        a: 4,
        b: 3,
        answer: 12,
        objectType: "book",
        hint: "4 baris × 3 kolom buku: 3 + 3 + 3 + 3 = ?",
        explanation: "4 baris × 3 buku = 12 buku cerita.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Susunan Baris dan Kolom (Array)",
      instructions: "Hitung total objek berdasarkan susunan baris dan kolom yang teratur.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "visual",
          storyText: "Tempat parkir memiliki 2 baris mobil. Setiap baris memuat 4 mobil.",
          question: "Berapa total mobil di tempat parkir?",
          a: 2,
          b: 4,
          answer: 8,
          objectType: "car",
          unit: "mobil",
          hint: "2 baris × 4 kolom mobil = ?",
        },
        {
          id: "ws-2",
          number: 2,
          type: "visual",
          storyText: "Rak toko kue menyusun biskuit dalam 3 baris. Tiap baris berisi 5 kue.",
          question: "Berapa banyak kue di rak tersebut?",
          a: 3,
          b: 5,
          answer: 15,
          objectType: "cookie",
          unit: "kue",
          hint: "3 baris × 5 kolom = ?",
        },
        {
          id: "ws-3",
          number: 3,
          type: "story",
          storyText: "Di pameran ada 4 baris sepeda motor baru. Setiap baris berisi 3 motor.",
          question: "Berapa total motor di pameran?",
          a: 4,
          b: 3,
          answer: 12,
          objectType: "motorcycle",
          unit: "motor",
          hint: "4 baris × 3 kolom = ?",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitunglah susunan perkalian berikut: 5 baris × 3 kolom = ...",
          a: 5,
          b: 3,
          answer: 15,
          hint: "5 × 3 = 15",
        },
        {
          id: "ws-5",
          number: 5,
          type: "direct",
          question: "Hitunglah susunan perkalian berikut: 2 baris × 5 kolom = ...",
          a: 2,
          b: 5,
          answer: 10,
          hint: "2 × 5 = 10",
        },
      ],
    },
  },
  {
    id: "mult-facts",
    operation: "multiplication",
    title: "Fakta Hitung Perkalian",
    subtitle: "Mengingat perkalian dengan urutan yang memudahkan",
    description: "Memperkuat fakta hitung perkalian dimulai dari ×1, ×2, ×10, ×5 hingga tabel lainnya.",
    prerequisites: ["mult-arrays"],
    representations: ["number-line"],
    difficulty: 3,
    conceptTitle: "Pola Angka dan Pelompatan",
    conceptExplanation: "Perkalian dapat dipahami sebagai lompatan berulang dengan jarak yang sama pada garis bilangan. Misalnya 6 × 4 berarti melompat sejauh 4 satuan sebanyak 6 kali hingga tiba di angka 24.",
    exampleA: 6,
    exampleB: 4,
    strategy: "repeated-addition",
    objectType: "pencil",
    mathForm: {
      title: "Lompatan Teratur pada Garis Bilangan",
      repeatedExpression: "4 + 4 + 4 + 4 + 4 + 4 = 24",
      standardExpression: "6 × 4 = 24",
      terms: [
        { term: "6", role: "Banyak Lompatan", explanation: "Melompat 6 kali ke kanan pada garis bilangan." },
        { term: "×", role: "Tanda Kali", explanation: "Menandakan lompatan yang sama berulang kali." },
        { term: "4", role: "Ukuran Lompatan", explanation: "Setiap lompatan melangkah 4 satuan." },
        { term: "=", role: "Sama Dengan", explanation: "Menunjukkan posisi mendarat di garis bilangan." },
        { term: "24", role: "Hasil Akhir", explanation: "Titik akhir lompatan pada garis bilangan." },
      ],
      note: "Mengetahui lompatan bilangan kelipatan membuat perkalian terasa lebih cepat dan mudah.",
    },
    guidedPractice: {
      prompt: "Berapakah hasil dari 7 dikali 5?",
      a: 7,
      b: 5,
      answer: 35,
      hint: "Lompat 5 sebanyak 7 kali: 5, 10, 15, 20, 25, 30, ...",
      objectType: "marble",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Lompat 4 (6 Kali)",
        title: "Kotak Pensil: 6 Pak Isi 4",
        context: "Sebuah toko menyediakan 6 kotak pensil. Setiap kotak berisi 4 batang pensil kayu.",
        a: 6,
        b: 4,
        objectType: "pencil",
        repeatedExpression: "4 + 4 + 4 + 4 + 4 + 4 = 24",
        standardExpression: "6 × 4 = 24",
        explanationNote: "Melompat 4 sebanyak 6 kali tiba di angka 24.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Kelipatan 5",
        title: "Kantong Kelereng: 7 Kantong Isi 5",
        context: "Doni mengumpulkan 7 kantong kelereng. Setiap kantong berisi 5 butir kelereng.",
        a: 7,
        b: 5,
        objectType: "marble",
        repeatedExpression: "5 + 5 + 5 + 5 + 5 + 5 + 5 = 35",
        standardExpression: "7 × 5 = 35",
        explanationNote: "Kelipatan 5: 5, 10, 15, 20, 25, 30, 35.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Lompat 3",
        title: "Piring Apel: 8 Piring Isi 3",
        context: "Di atas meja prasmanan ada 8 piring kecil. Setiap piring berisi 3 buah apel segar.",
        a: 8,
        b: 3,
        objectType: "apple",
        repeatedExpression: "3 + 3 + 3 + 3 + 3 + 3 + 3 + 3 = 24",
        standardExpression: "8 × 3 = 24",
        explanationNote: "8 lompatan sejauh 3 langkah mencapai angka 24.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Kelipatan 2 (Genap)",
        title: "Kantong Jeruk: 9 Kantong Isi 2",
        context: "Ibu menyiapkan 9 bungkus oleh-oleh. Setiap bungkus berisi 2 buah jeruk manis.",
        a: 9,
        b: 2,
        objectType: "orange",
        repeatedExpression: "2 + 2 + 2 + 2 + 2 + 2 + 2 + 2 + 2 = 18",
        standardExpression: "9 × 2 = 18",
        explanationNote: "Bilangan genap kelipatan 2: 2, 4, 6, 8, 10, 12, 14, 16, 18.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Kotak Pensil Toko ATK",
        story: "Di etalase toko alat tulis, terdapat 6 kotak pensil baru. Setiap kotak berisi 4 batang pensil.",
        question: "Berapa total pensil yang ada di etalase tersebut?",
        a: 6,
        b: 4,
        answer: 24,
        objectType: "pencil",
        hint: "Lompat 4 sebanyak 6 kali pada garis bilangan: 4, 8, 12, 16, 20, 24.",
        explanation: "6 kotak × 4 pensil = 24 batang pensil.",
      },
      {
        id: "sp-2",
        title: "Kantong Kelereng Doni",
        story: "Doni membagikan kelereng ke dalam 7 kantong kain. Setiap kantong berisi tepat 5 butir kelereng.",
        question: "Berapa butir kelereng Doni seluruhnya?",
        a: 7,
        b: 5,
        answer: 35,
        objectType: "marble",
        hint: "Hitung kelipatan 5 sebanyak 7 kali: 5, 10, 15, 20, 25, 30, 35.",
        explanation: "7 kantong × 5 kelereng = 35 butir kelereng.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Fakta Hitung Perkalian",
      instructions: "Tentukan hasil perkalian menggunakan pola lompatan garis bilangan atau penjumlahan berulang.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "visual",
          storyText: "Ada 4 kotak pensil yang masing-masing berisi 5 pensil kayu.",
          question: "Berapa total pensil pada garis bilangan tersebut?",
          a: 4,
          b: 5,
          answer: 20,
          objectType: "pencil",
          unit: "pensil",
          hint: "Lompat 5 sebanyak 4 kali: 5, 10, 15, 20.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "visual",
          storyText: "Doni melompat 3 satuan sebanyak 5 kali.",
          question: "Di angka berapakah Doni mendarat pada garis bilangan?",
          a: 5,
          b: 3,
          answer: 15,
          objectType: "marble",
          unit: "langkah",
          hint: "5 lompatan × 3 satuan = ?",
        },
        {
          id: "ws-3",
          number: 3,
          type: "story",
          storyText: "Paman menaruh apel ke dalam 6 keranjang. Setiap keranjang berisi 5 buah apel segar.",
          question: "Berapa jumlah seluruh apel di dalam 6 keranjang?",
          a: 6,
          b: 5,
          answer: 30,
          objectType: "apple",
          unit: "apel",
          hint: "6 × 5 = 30",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitunglah hasil perkalian kelipatan berikut: 7 × 4 = ...",
          a: 7,
          b: 4,
          answer: 28,
          hint: "7 × 4 = 28",
        },
        {
          id: "ws-5",
          number: 5,
          type: "direct",
          question: "Hitunglah hasil perkalian kelipatan berikut: 8 × 5 = ...",
          a: 8,
          b: 5,
          answer: 40,
          hint: "8 × 5 = 40",
        },
      ],
    },
  },

  // --- PENJUMLAHAN ---
  {
    id: "add-up-to-10",
    operation: "addition",
    title: "Menggabungkan Sampai 10",
    subtitle: "Konsep dasar penjumlahan benda konkret",
    description: "Memahami konsep menggabungkan dua himpunan benda untuk mencari jumlah keseluruhannya.",
    prerequisites: [],
    representations: ["counters", "ten-frame"],
    difficulty: 1,
    conceptTitle: "Menggabungkan Dua Kelompok",
    conceptExplanation: "Penjumlahan berarti mengumpulkan dua atau lebih kelompok benda menjadi satu kesatuan utuh.",
    exampleA: 4,
    exampleB: 3,
    strategy: "count-on",
    objectType: "marble",
    mathForm: {
      title: "Bentuk Penjumlahan Menggabungkan",
      standardExpression: "4 + 3 = 7",
      terms: [
        { term: "4", role: "Suku Pertama", explanation: "Banyak benda di kelompok pertama." },
        { term: "+", role: "Tanda Tambah", explanation: "Menggabungkan dua kelompok menjadi satu." },
        { term: "3", role: "Suku Kedua", explanation: "Banyak benda di kelompok kedua." },
        { term: "=", role: "Sama Dengan", explanation: "Menunjukkan total yang setara." },
        { term: "7", role: "Jumlah Total", explanation: "Total seluruh benda setelah digabungkan." },
      ],
      note: "Urutan bilangan dapat ditukar tanpa mengubah hasil (4 + 3 = 3 + 4 = 7).",
    },
    guidedPractice: {
      prompt: "Ada 5 kelereng biru dan 3 kelereng merah. Berapa jumlah seluruh kelereng?",
      a: 5,
      b: 3,
      answer: 8,
      hint: "Mulai dari 5, lalu hitung maju 3 langkah: 6, 7, 8.",
      objectType: "marble",
      color: "#2563eb",
      secondColor: "#dc2626",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Bilangan Kecil",
        title: "2 + 3 Kelereng",
        context: "Ada 2 kelereng biru di wadah, lalu digabungkan dengan 3 kelereng merah.",
        a: 2,
        b: 3,
        objectType: "marble",
        color: "#2563eb",
        secondColor: "#dc2626",
        standardExpression: "2 + 3 = 5",
        explanationNote: "Mulai dari 2, hitung maju 3 langkah: 3, 4, 5.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Menuju Sepuluh",
        title: "4 + 6 Apel",
        context: "Ibu membeli 4 buah apel manis lalu ayah membeli 6 buah apel lagi.",
        a: 4,
        b: 6,
        objectType: "apple",
        standardExpression: "4 + 6 = 10",
        explanationNote: "Pasangan bilangan pembentuk 10 utuh.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Bilangan Kembar (Doubles)",
        title: "4 + 4 Kue",
        context: "Ada 4 kue cokelat dan 4 kue stroberi di atas piring.",
        a: 4,
        b: 4,
        objectType: "cookie",
        standardExpression: "4 + 4 = 8",
        explanationNote: "Mengingat bilangan kembar mempermudah perhitungan mental.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Ditambah Nol (0)",
        title: "5 + 0 Jeruk",
        context: "Ada 5 jeruk di meja, tidak ada jeruk baru yang ditambahkan.",
        a: 5,
        b: 0,
        objectType: "orange",
        standardExpression: "5 + 0 = 5",
        explanationNote: "Menambahkan 0 tidak mengubah jumlah awal.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Koleksi Kelereng Andi",
        story: "Andi memiliki 5 butir kelereng di sakunya. Kakak memberinya 4 butir kelereng lagi.",
        question: "Berapa banyak kelereng Andi sekarang?",
        a: 5,
        b: 4,
        answer: 9,
        objectType: "marble",
        hint: "Mulai dari 5, hitung maju 4 langkah: 6, 7, 8, 9.",
        explanation: "5 + 4 = 9 butir kelereng.",
      },
      {
        id: "sp-2",
        title: "Apel di Keranjang Meja",
        story: "Ada 3 buah apel merah di keranjang meja. Ibu memasukkan lagi 4 buah apel segar.",
        question: "Berapa total apel di keranjang sekarang?",
        a: 3,
        b: 4,
        answer: 7,
        objectType: "apple",
        hint: "3 apel mula-mula + 4 apel tambahan = ?",
        explanation: "3 + 4 = 7 buah apel.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Menggabungkan Objek Sampai 10",
      instructions: "Gabungkan kelompok benda atau hitung hasil penjumlahan langsung.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "visual",
          storyText: "Ada 4 kelereng biru dan 3 kelereng merah digabungkan.",
          question: "Berapa jumlah seluruh kelereng?",
          a: 4,
          b: 3,
          answer: 7,
          objectType: "marble",
          color: "#2563eb",
          secondColor: "#dc2626",
          unit: "kelereng",
          hint: "4 + 3 = ?",
        },
        {
          id: "ws-2",
          number: 2,
          type: "visual",
          storyText: "Ada 5 apel di piring dan 2 apel di meja.",
          question: "Berapa jumlah seluruh apel?",
          a: 5,
          b: 2,
          answer: 7,
          objectType: "apple",
          unit: "apel",
          hint: "5 + 2 = ?",
        },
        {
          id: "ws-3",
          number: 3,
          type: "story",
          storyText: "Adik memetik 6 jeruk manis. Paman memberinya 3 jeruk lagi.",
          question: "Berapa jeruk adik sekarang?",
          a: 6,
          b: 3,
          answer: 9,
          objectType: "orange",
          unit: "jeruk",
          hint: "6 + 3 = ?",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitunglah: 7 + 2 = ...",
          a: 7,
          b: 2,
          answer: 9,
          hint: "Mulai dari 7, hitung maju 2",
        },
        {
          id: "ws-5",
          number: 5,
          type: "direct",
          question: "Hitunglah: 6 + 4 = ...",
          a: 6,
          b: 4,
          answer: 10,
          hint: "Pasangan 10 utuh",
        },
      ],
    },
  },
  {
    id: "add-make-ten",
    operation: "addition",
    title: "Strategi Menuju 10 (Make Ten)",
    subtitle: "Menguraikan bilangan agar membentuk puluhan utuh",
    description: "Strategi menjumlahkan dengan cara melengkapi bilangan pertama menjadi 10 terlebih dahulu.",
    prerequisites: ["add-up-to-10"],
    representations: ["ten-frame"],
    difficulty: 2,
    conceptTitle: "Bentuk 10 Terlebih Dahulu",
    conceptExplanation: "Ketika menjumlahkan angka seperti 8 + 7, lebih mudah mengambil 2 dari 7 agar 8 menjadi 10 utuh. Sisanya tinggal 5, sehingga 10 + 5 = 15.",
    exampleA: 8,
    exampleB: 7,
    strategy: "make-ten",
    objectType: "apple",
    mathForm: {
      title: "Strategi Menuju 10",
      repeatedExpression: "8 + 2 + 5 = 10 + 5 = 15",
      standardExpression: "8 + 7 = 15",
      terms: [
        { term: "8", role: "Bilangan Awal", explanation: "Membutuhkan 2 agar menjadi 10 penuh." },
        { term: "7", role: "Pengurai (2 + 5)", explanation: "Diuraikan menjadi 2 (ke 10) dan 5 (sisa)." },
        { term: "10", role: "Puluhan Lengkap", explanation: "8 + 2 = 10." },
        { term: "5", role: "Sisa Satuan", explanation: "Sisa yang ditambahkan ke puluhan." },
        { term: "15", role: "Hasil Akhir", explanation: "10 + 5 = 15." },
      ],
      note: "Melengkapi puluhan 10 mempermudah perhitungan mental bilangan besar.",
    },
    guidedPractice: {
      prompt: "Berapa 9 + 6 dengan strategi menuju 10?",
      a: 9,
      b: 6,
      answer: 15,
      hint: "9 butuh 1 agar jadi 10. Ambil 1 dari 6 (sisa 5). Maka 10 + 5 = ?",
      objectType: "orange",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: 8 Butuh 2",
        title: "Keranjang Apel: 8 + 7",
        context: "Ada 8 apel merah di keranjang dan 7 apel hijau di meja. Ambil 2 apel hijau untuk melengkapi 8 menjadi 10.",
        a: 8,
        b: 7,
        objectType: "apple",
        color: "#ef4444",
        secondColor: "#22c55e",
        repeatedExpression: "(8 + 2) + 5 = 10 + 5 = 15",
        standardExpression: "8 + 7 = 15",
        explanationNote: "8 + 2 = 10, lalu 10 + 5 = 15 buah apel.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: 9 Butuh 1",
        title: "Piring Jeruk: 9 + 5",
        context: "Paman menaruh 9 jeruk manis di piring besar dan 5 jeruk di piring kecil. 9 hanya butuh 1 agar jadi 10.",
        a: 9,
        b: 5,
        objectType: "orange",
        color: "#ea580c",
        secondColor: "#f59e0b",
        repeatedExpression: "(9 + 1) + 4 = 10 + 4 = 14",
        standardExpression: "9 + 5 = 14",
        explanationNote: "9 + 1 = 10, lalu 10 + 4 = 14 buah jeruk.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: 8 Butuh 2",
        title: "Toples Biskuit: 8 + 5",
        context: "Di toples ada 8 biskuit cokelat dan 5 biskuit keju. Lengkapi 8 menjadi 10 dengan mengambil 2.",
        a: 8,
        b: 5,
        objectType: "cookie",
        repeatedExpression: "(8 + 2) + 3 = 10 + 3 = 13",
        standardExpression: "8 + 5 = 13",
        explanationNote: "8 + 2 = 10, lalu 10 + 3 = 13 keping biskuit.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: 7 Butuh 3",
        title: "Koleksi Kelereng: 7 + 6",
        context: "Ada 7 kelereng biru dan 6 kelereng merah. Ambil 3 kelereng merah agar 7 kelereng biru menjadi 10 utuh.",
        a: 7,
        b: 6,
        objectType: "marble",
        color: "#2563eb",
        secondColor: "#dc2626",
        repeatedExpression: "(7 + 3) + 3 = 10 + 3 = 13",
        standardExpression: "7 + 6 = 13",
        explanationNote: "7 + 3 = 10, lalu 10 + 3 = 13 butir kelereng.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Apel Segar di Meja Makan",
        story: "Di atas meja makan terdapat 8 buah apel merah. Ibu membawakan lagi 7 buah apel hijau segar dari pasar.",
        question: "Berapa total buah apel yang ada di meja makan sekarang?",
        a: 8,
        b: 7,
        answer: 15,
        objectType: "apple",
        color: "#ef4444",
        secondColor: "#22c55e",
        hint: "8 butuh 2 dari 7 agar menjadi 10 penuh. Sisanya tinggal 5 apel. 10 + 5 = ?",
        explanation: "8 apel merah + 7 apel hijau = (8 + 2) + 5 = 10 + 5 = 15 buah apel.",
      },
      {
        id: "sp-2",
        title: "Kelereng Hadiah Kakak",
        story: "Raka memiliki 9 butir kelereng biru di toplesnya. Kakak memberikan 6 butir kelereng merah sebagai hadiah ulang tahun.",
        question: "Berapa butir kelereng Raka sekarang seluruhnya?",
        a: 9,
        b: 6,
        answer: 15,
        objectType: "marble",
        color: "#2563eb",
        secondColor: "#dc2626",
        hint: "9 butuh 1 agar jadi 10. Ambil 1 dari 6 (sisa 5). Maka 10 + 5 = ?",
        explanation: "9 kelereng biru + 6 kelereng merah = (9 + 1) + 5 = 10 + 5 = 15 butir kelereng.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Strategi Menuju 10 (Make Ten)",
      instructions: "Lengkapi bilangan pertama menjadi 10 utuh, lalu jumlahkan sisa satuannya.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "visual",
          storyText: "Ada 8 apel merah dan 6 apel hijau dalam bingkai sepuluh.",
          question: "Berapa jumlah seluruh apel tersebut?",
          a: 8,
          b: 6,
          answer: 14,
          objectType: "apple",
          color: "#ef4444",
          secondColor: "#22c55e",
          unit: "apel",
          hint: "8 butuh 2 agar jadi 10. Sisa 4 apel. 10 + 4 = 14.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "visual",
          storyText: "Ada 9 kelereng biru dan 4 kelereng merah.",
          question: "Berapa total kelereng jika digabungkan?",
          a: 9,
          b: 4,
          answer: 13,
          objectType: "marble",
          color: "#2563eb",
          secondColor: "#dc2626",
          unit: "kelereng",
          hint: "9 butuh 1 agar jadi 10. Sisa 3. 10 + 3 = 13.",
        },
        {
          id: "ws-3",
          number: 3,
          type: "story",
          storyText: "Di toples ada 8 biskuit rasa cokelat dan 5 biskuit rasa vanila.",
          question: "Berapa banyak biskuit seluruhnya di dalam toples?",
          a: 8,
          b: 5,
          answer: 13,
          objectType: "cookie",
          unit: "biskuit",
          hint: "8 + 2 = 10, lalu 10 + 3 = 13.",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitunglah dengan strategi menuju 10: 9 + 7 = ...",
          a: 9,
          b: 7,
          answer: 16,
          hint: "9 + 1 = 10; 10 + 6 = 16",
        },
        {
          id: "ws-5",
          number: 5,
          type: "direct",
          question: "Hitunglah dengan strategi menuju 10: 7 + 5 = ...",
          a: 7,
          b: 5,
          answer: 12,
          hint: "7 + 3 = 10; 10 + 2 = 12",
        },
      ],
    },
  },
  {
    id: "add-two-digit",
    operation: "addition",
    title: "Dekomposisi Nilai Tempat",
    subtitle: "Menjumlahkan dua digit: puluhan dengan puluhan, satuan dengan satuan",
    description: "Menguraikan bilangan dua digit ke dalam nilai tempatnya agar mudah dihitung.",
    prerequisites: ["add-make-ten"],
    representations: ["base-ten", "place-value"],
    difficulty: 3,
    conceptTitle: "Pisahkan Puluhan dan Satuan",
    conceptExplanation: "37 + 28 dapat diuraikan: (30 + 20) = 50 dan (7 + 8) = 15. Kemudian 50 + 15 = 65.",
    exampleA: 37,
    exampleB: 28,
    strategy: "decompose-place-value",
    objectType: "book",
    mathForm: {
      title: "Pemisahan Nilai Tempat",
      repeatedExpression: "(30 + 20) + (7 + 8) = 50 + 15 = 65",
      standardExpression: "37 + 28 = 65",
      terms: [
        { term: "37", role: "Bilangan Pertama", explanation: "3 puluhan (30) dan 7 satuan." },
        { term: "28", role: "Bilangan Kedua", explanation: "2 puluhan (20) dan 8 satuan." },
        { term: "50", role: "Jumlah Puluhan", explanation: "30 + 20 = 50." },
        { term: "15", role: "Jumlah Satuan", explanation: "7 + 8 = 15." },
        { term: "65", role: "Hasil Akhir", explanation: "50 + 15 = 65." },
      ],
      note: "Jumlahkan nilai tempat yang sejenis: puluhan dengan puluhan, satuan dengan satuan.",
    },
    guidedPractice: {
      prompt: "Hitung 24 + 15 dengan memisahkan puluhan dan satuan.",
      a: 24,
      b: 15,
      answer: 39,
      hint: "Puluhan: 20 + 10 = 30. Satuan: 4 + 5 = 9. Total = ?",
      objectType: "pencil",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Tanpa Menyimpan",
        title: "Koleksi Pensil: 24 + 15",
        context: "Ada 24 pensil hitam dan 15 pensil biru. Jumlahkan puluhannya (20 + 10 = 30) lalu satuannya (4 + 5 = 9).",
        a: 24,
        b: 15,
        objectType: "pencil",
        repeatedExpression: "(20 + 10) + (4 + 5) = 30 + 9 = 39",
        standardExpression: "24 + 15 = 39",
        explanationNote: "30 + 9 = 39 batang pensil.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Menyimpan Puluhan",
        title: "Tumpukan Buku: 37 + 28",
        context: "Perpustakaan menerima 37 buku cerita dan 28 buku gambar. Satuan 7 + 8 = 15 menghasilkan 1 puluhan baru.",
        a: 37,
        b: 28,
        objectType: "book",
        repeatedExpression: "(30 + 20) + (7 + 8) = 50 + 15 = 65",
        standardExpression: "37 + 28 = 65",
        explanationNote: "50 + 15 = 65 buku bacaan.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Puluhan Besar",
        title: "Keranjang Telur: 45 + 23",
        context: "Peternak memanen 45 butir telur ayam dan 23 butir telur bebek. Jumlahkan: 40 + 20 = 60, dan 5 + 3 = 8.",
        a: 45,
        b: 23,
        objectType: "egg",
        repeatedExpression: "(40 + 20) + (5 + 3) = 60 + 8 = 68",
        standardExpression: "45 + 23 = 68",
        explanationNote: "60 + 8 = 68 butir telur.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Menyimpan Puluhan Besar",
        title: "Kotak Biskuit: 56 + 37",
        context: "Toko kue memanggang 56 biskuit cokelat dan 37 biskuit vanila. Satuan 6 + 7 = 13 (10 + 3).",
        a: 56,
        b: 37,
        objectType: "cookie",
        repeatedExpression: "(50 + 30) + (6 + 7) = 80 + 13 = 93",
        standardExpression: "56 + 37 = 93",
        explanationNote: "80 + 13 = 93 keping biskuit.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Kiriman Buku Perpustakaan",
        story: "Perpustakaan desa menerima kiriman 34 buku cerita anak di pagi hari dan 25 buku ensiklopedia di siang hari.",
        question: "Berapa total buku yang diterima perpustakaan hari ini?",
        a: 34,
        b: 25,
        answer: 59,
        objectType: "book",
        hint: "Pisahkan nilai tempat: puluhan (30 + 20 = 50) dan satuan (4 + 5 = 9). 50 + 9 = ?",
        explanation: "34 buku + 25 buku = (30 + 20) + (4 + 5) = 50 + 9 = 59 buku.",
      },
      {
        id: "sp-2",
        title: "Persediaan Pensil Koperasi",
        story: "Koperasi sekolah memiliki persediaan 48 pensil hitam dan membeli lagi 36 pensil warna untuk stok ujian.",
        question: "Berapa banyak pensil yang tersedia di koperasi sekolah sekarang?",
        a: 48,
        b: 36,
        answer: 84,
        objectType: "pencil",
        hint: "Puluhan: 40 + 30 = 70. Satuan: 8 + 6 = 14. 70 + 14 = ?",
        explanation: "48 pensil + 36 pensil = (40 + 30) + (8 + 6) = 70 + 14 = 84 batang pensil.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Dekomposisi Nilai Tempat",
      instructions: "Uraikan bilangan menjadi puluhan dan satuan, lalu jumlahkan masing-masing nilai tempat.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "visual",
          storyText: "Ada 23 buku cerita dan 14 buku ensiklopedia di rak buku balok.",
          question: "Berapa jumlah seluruh buku?",
          a: 23,
          b: 14,
          answer: 37,
          objectType: "book",
          unit: "buku",
          hint: "Puluhan: 20 + 10 = 30. Satuan: 3 + 4 = 7. Total = 37.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "visual",
          storyText: "Ada 35 pensil hitam dan 22 pensil warna di kotak alat tulis.",
          question: "Berapa banyak pensil seluruhnya?",
          a: 35,
          b: 22,
          answer: 57,
          objectType: "pencil",
          unit: "pensil",
          hint: "Puluhan: 30 + 20 = 50. Satuan: 5 + 2 = 7. Total = 57.",
        },
        {
          id: "ws-3",
          number: 3,
          type: "story",
          storyText: "Peternak mengumpulkan 42 butir telur ayam kampung dan 26 butir telur bebek.",
          question: "Berapa total butir telur yang dikumpulkan?",
          a: 42,
          b: 26,
          answer: 68,
          objectType: "egg",
          unit: "butir",
          hint: "Puluhan: 40 + 20 = 60. Satuan: 2 + 6 = 8. 60 + 8 = 68.",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitunglah dengan memisahkan puluhan dan satuan: 36 + 27 = ...",
          a: 36,
          b: 27,
          answer: 63,
          hint: "(30 + 20) + (6 + 7) = 50 + 13 = 63",
        },
        {
          id: "ws-5",
          number: 5,
          type: "direct",
          question: "Hitunglah dengan memisahkan puluhan dan satuan: 54 + 38 = ...",
          a: 54,
          b: 38,
          answer: 92,
          hint: "(50 + 30) + (4 + 8) = 80 + 12 = 92",
        },
      ],
    },
  },

  // --- PENGURANGAN ---
  {
    id: "sub-up-to-10",
    operation: "subtraction",
    title: "Mengambil Objek Sampai 10",
    subtitle: "Konsep dasar pengurangan sebagai sisa atau selisih",
    description: "Memahami pengurangan sebagai proses memisahkan sejumlah benda dari kumpulan mula-mula.",
    prerequisites: ["add-up-to-10"],
    representations: ["number-line", "counters"],
    difficulty: 1,
    conceptTitle: "Berapa yang Tersisa?",
    conceptExplanation: "Pengurangan terjadi ketika kita mengambil sebagian kue dari piring, menyisakan kue yang belum dimakan.",
    exampleA: 7,
    exampleB: 3,
    strategy: "count-back",
    objectType: "cookie",
    mathForm: {
      title: "Bentuk Pengurangan Mengambil",
      standardExpression: "7 − 3 = 4",
      terms: [
        { term: "7", role: "Bilangan Mula-mula", explanation: "Jumlah seluruh benda awal sebelum diambil." },
        { term: "−", role: "Tanda Kurang", explanation: "Menyatakan pengambilan atau selisih." },
        { term: "3", role: "Bilangan Pengurang", explanation: "Banyak benda yang diambil." },
        { term: "=", role: "Sama Dengan", explanation: "Menunjukkan sisa yang setara." },
        { term: "4", role: "Sisa / Selisih", explanation: "Banyak benda yang tersisa." },
      ],
      note: "Pengurangan bersifat tidak komutatif (7 − 3 ≠ 3 − 7). Bilangan awal harus lebih besar atau sama.",
    },
    guidedPractice: {
      prompt: "Ada 8 kue di atas piring. Dimakan 3 kue. Berapa kue yang tersisa?",
      a: 8,
      b: 3,
      answer: 5,
      hint: "Mulai dari 8, hitung mundur 3 langkah: 7, 6, 5.",
      objectType: "cookie",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Kue Dimakan",
        title: "7 Kue Dimakan 3",
        context: "Ada 7 kue di piring. Dimakan 3 potong kue oleh adik.",
        a: 7,
        b: 3,
        objectType: "cookie",
        standardExpression: "7 − 3 = 4",
        explanationNote: "Mulai dari 7, hitung mundur 3 langkah: 6, 5, 4.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Telur Terpakai",
        title: "8 Telur Dipakai 4",
        context: "Ibu memiliki 8 butir telur. Digunakan 4 butir untuk membuat martabak manis.",
        a: 8,
        b: 4,
        objectType: "egg",
        standardExpression: "8 − 4 = 4",
        explanationNote: "Mengurangkan separuh (kebalikan dari kembar 4 + 4).",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Habis (Kurang Bilangan Sama)",
        title: "5 Pensil Dibagikan Semua",
        context: "Ada 5 pensil di kotak. Kelima pensil dibagikan habis ke teman sekelas.",
        a: 5,
        b: 5,
        objectType: "pencil",
        standardExpression: "5 − 5 = 0",
        explanationNote: "Jika sebuah bilangan dikurangi oleh dirinya sendiri, hasilnya selalu 0.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Kurang Satu (Bilangan Sebelum)",
        title: "6 Apel Dimakan 1",
        context: "Ada 6 apel merah di keranjang. Dimakan 1 buah apel.",
        a: 6,
        b: 1,
        objectType: "apple",
        standardExpression: "6 − 1 = 5",
        explanationNote: "Mengurangi 1 sama dengan mencari bilangan tepat sebelum 6.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Kue di Meja Makan",
        story: "Ada 8 potong kue biskuit di atas piring. Adik dan teman-temannya memakan 3 potong kue.",
        question: "Berapa potong kue yang masih tersisa di piring?",
        a: 8,
        b: 3,
        answer: 5,
        objectType: "cookie",
        hint: "Mulai dari 8, hitung mundur 3: 7, 6, 5.",
        explanation: "8 kue mula-mula − 3 kue dimakan = 5 kue tersisa.",
      },
      {
        id: "sp-2",
        title: "Telur untuk Adonan Roti",
        story: "Di dapur terdapat 9 butir telur ayam. Ibu mengambil 4 butir untuk membuat bolu kukus.",
        question: "Berapa butir telur yang belum digunakan?",
        a: 9,
        b: 4,
        answer: 5,
        objectType: "egg",
        hint: "9 telur − 4 telur terpakai: 9, 8, 7, 6, 5.",
        explanation: "9 − 4 = 5 butir telur.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Mengambil Objek Sampai 10",
      instructions: "Hitung sisa benda setelah diambil atau dimakan.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "visual",
          storyText: "Ada 8 kue biskuit di piring. Dimakan 3 kue.",
          question: "Berapa kue yang tersisa?",
          a: 8,
          b: 3,
          answer: 5,
          objectType: "cookie",
          unit: "kue",
          hint: "8 − 3 = ?",
        },
        {
          id: "ws-2",
          number: 2,
          type: "visual",
          storyText: "Ada 7 butir telur di mangkuk. Dipakai 2 butir.",
          question: "Berapa butir telur tersisa?",
          a: 7,
          b: 2,
          answer: 5,
          objectType: "egg",
          unit: "butir telur",
          hint: "7 − 2 = ?",
        },
        {
          id: "ws-3",
          number: 3,
          type: "story",
          storyText: "Rian memiliki 6 batang pensil. Sebanyak 2 pensil dipinjamkan ke adik.",
          question: "Berapa pensil Rian sekarang?",
          a: 6,
          b: 2,
          answer: 4,
          objectType: "pencil",
          unit: "pensil",
          hint: "6 − 2 = ?",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitunglah: 9 − 3 = ...",
          a: 9,
          b: 3,
          answer: 6,
          hint: "Hitung mundur 3 dari 9",
        },
        {
          id: "ws-5",
          number: 5,
          type: "direct",
          question: "Hitunglah: 10 − 4 = ...",
          a: 10,
          b: 4,
          answer: 6,
          hint: "10 dikurang 4",
        },
      ],
    },
  },
  {
    id: "sub-bridge-ten",
    operation: "subtraction",
    title: "Pengurangan Melewati 10",
    subtitle: "Strategi mundur bertahap melalui angka 10",
    description: "Mengurangkan bilangan belasan dengan cara mengurangkan satuannya terlebih dahulu menuju 10.",
    prerequisites: ["sub-up-to-10"],
    representations: ["number-line", "ten-frame"],
    difficulty: 2,
    conceptTitle: "Singgah di Angka 10",
    conceptExplanation: "Untuk 13 - 5, kurangkan 3 terlebih dahulu agar sampai di 10. Lalu kurangkan sisa 2 dari 10, menghasilkan 8.",
    exampleA: 13,
    exampleB: 5,
    strategy: "bridge-ten",
    objectType: "cookie",
    mathForm: {
      title: "Strategi Singgah di Angka 10",
      repeatedExpression: "(13 − 3) − 2 = 10 − 2 = 8",
      standardExpression: "13 − 5 = 8",
      terms: [
        { term: "13", role: "Bilangan Belasan", explanation: "Dikurangi 3 agar menjadi 10 utuh." },
        { term: "5", role: "Pengurang (3 + 2)", explanation: "Diuraikan menjadi 3 (ke 10) dan 2 (sisa pengurang)." },
        { term: "10", role: "Halte Puluhan", explanation: "13 − 3 = 10." },
        { term: "2", role: "Sisa Pengurang", explanation: "Dikurangkan dari 10." },
        { term: "8", role: "Hasil Akhir", explanation: "10 − 2 = 8." },
      ],
      note: "Singgah di 10 mengubah pengurangan belasan menjadi pengurangan basis 10 yang sederhana.",
    },
    guidedPractice: {
      prompt: "Hitung 14 - 6 dengan singgah di angka 10.",
      a: 14,
      b: 6,
      answer: 8,
      hint: "14 - 4 = 10. Kita masih harus mengurang 2 lagi. 10 - 2 = ?",
      objectType: "apple",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Mundur 3 lalu 2",
        title: "Toples Biskuit: 13 − 5",
        context: "Ada 13 biskuit di toples. Kurangi 3 biskuit dulu agar tersisa 10, lalu kurangi 2 biskuit lagi.",
        a: 13,
        b: 5,
        objectType: "cookie",
        repeatedExpression: "(13 − 3) − 2 = 10 − 2 = 8",
        standardExpression: "13 − 5 = 8",
        explanationNote: "13 − 3 = 10, lalu 10 − 2 = 8 biskuit tersisa.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Mundur 4 lalu 2",
        title: "Keranjang Apel: 14 − 6",
        context: "Di keranjang ada 14 buah apel. Ambil 4 apel untuk menuju 10, lalu ambil 2 apel lagi dari 10.",
        a: 14,
        b: 6,
        objectType: "apple",
        repeatedExpression: "(14 − 4) − 2 = 10 − 2 = 8",
        standardExpression: "14 − 6 = 8",
        explanationNote: "14 − 4 = 10, lalu 10 − 2 = 8 buah apel.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Mundur 5 lalu 3",
        title: "Wadah Telur: 15 − 8",
        context: "Ada 15 butir telur di wadah. Ambil 5 butir menuju 10, lalu ambil 3 butir lagi.",
        a: 15,
        b: 8,
        objectType: "egg",
        repeatedExpression: "(15 − 5) − 3 = 10 − 3 = 7",
        standardExpression: "15 − 8 = 7",
        explanationNote: "15 − 5 = 10, lalu 10 − 3 = 7 butir telur.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Mundur 2 lalu 5",
        title: "Kantung Jeruk: 12 − 7",
        context: "Di kantung ada 12 buah jeruk. Keluarkan 2 buah agar pas 10, lalu keluarkan 5 buah lagi.",
        a: 12,
        b: 7,
        objectType: "orange",
        repeatedExpression: "(12 − 2) − 5 = 10 − 5 = 5",
        standardExpression: "12 − 7 = 5",
        explanationNote: "12 − 2 = 10, lalu 10 − 5 = 5 buah jeruk.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Biskuit Cokelat Jam Istirahat",
        story: "Di toples ada 14 biskuit cokelat lezat. Saat jam istirahat, 6 biskuit dimakan bersama teman-teman.",
        question: "Berapa banyak biskuit yang tersisa di toples?",
        a: 14,
        b: 6,
        answer: 8,
        objectType: "cookie",
        hint: "Mundur ke 10: 14 − 4 = 10. Lalu kurangi sisa 2 dari 10: 10 − 2 = ?",
        explanation: "14 biskuit − 6 biskuit = (14 − 4) − 2 = 10 − 2 = 8 keping biskuit.",
      },
      {
        id: "sp-2",
        title: "Telur Bahan Kue Martabak",
        story: "Ibu membeli 15 butir telur di warung. Sebanyak 8 butir telur digunakan untuk adonan kue martabak manis.",
        question: "Berapa sisa butir telur yang belum dipakai?",
        a: 15,
        b: 8,
        answer: 7,
        objectType: "egg",
        hint: "Mundur ke 10: 15 − 5 = 10. Lalu kurangi sisa 3 dari 10: 10 − 3 = ?",
        explanation: "15 telur − 8 telur = (15 − 5) − 3 = 10 − 3 = 7 butir telur.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Pengurangan Melewati 10",
      instructions: "Kurangkan menuju 10 terlebih dahulu, kemudian kurangkan sisa pengurang dari 10.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "visual",
          storyText: "Ada 13 biskuit mula-mula, lalu diambil 6 biskuit.",
          question: "Berapa banyak biskuit yang tersisa?",
          a: 13,
          b: 6,
          answer: 7,
          objectType: "cookie",
          unit: "biskuit",
          hint: "13 − 3 = 10; 10 − 3 = 7.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "visual",
          storyText: "Ada 15 buah apel di keranjang, diambil 7 buah untuk dibagikan.",
          question: "Berapa sisa apel di keranjang sekarang?",
          a: 15,
          b: 7,
          answer: 8,
          objectType: "apple",
          unit: "apel",
          hint: "15 − 5 = 10; 10 − 2 = 8.",
        },
        {
          id: "ws-3",
          number: 3,
          type: "story",
          storyText: "Paman memiliki 14 butir telur di dapur dan menggunakan 8 butir untuk membuat lauk makan siang.",
          question: "Berapa sisa butir telur milik paman?",
          a: 14,
          b: 8,
          answer: 6,
          objectType: "egg",
          unit: "butir",
          hint: "14 − 4 = 10; 10 − 4 = 6.",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitunglah dengan melewati angka 10: 16 − 9 = ...",
          a: 16,
          b: 9,
          answer: 7,
          hint: "(16 − 6) − 3 = 10 − 3 = 7",
        },
        {
          id: "ws-5",
          number: 5,
          type: "direct",
          question: "Hitunglah dengan melewati angka 10: 12 − 5 = ...",
          a: 12,
          b: 5,
          answer: 7,
          hint: "(12 − 2) − 3 = 10 − 3 = 7",
        },
      ],
    },
  },

  // --- PEMBAGIAN ---
  {
    id: "div-sharing",
    operation: "division",
    title: "Pembagian sebagai Berbagi Rata (Sharing)",
    subtitle: "Membagi sejumlah benda ke dalam kelompok sama rata",
    description: "Memahami pembagian sebagai aktivitas membagikan benda satu per satu secara adil ke sejumlah wadah.",
    prerequisites: ["mult-equal-groups"],
    representations: ["equal-groups"],
    difficulty: 1,
    conceptTitle: "Membagi Sama Rata",
    conceptExplanation: "Jika ada 12 pensil dibagikan sama rata kepada 3 anak, setiap anak akan menerima 4 pensil.",
    exampleA: 12,
    exampleB: 3,
    strategy: "sharing",
    objectType: "pencil",
    mathForm: {
      title: "Bentuk Pembagian Berbagi Rata",
      repeatedExpression: "4 + 4 + 4 = 12  ⟺  3 × 4 = 12",
      standardExpression: "12 ÷ 3 = 4",
      terms: [
        { term: "12", role: "Total Benda (Dividen)", explanation: "Seluruh benda yang akan dibagikan." },
        { term: "÷", role: "Tanda Bagi", explanation: "Membagi sama rata ke beberapa wadah." },
        { term: "3", role: "Banyak Wadah (Pembagi)", explanation: "Banyak kelompok penerima." },
        { term: "=", role: "Sama Dengan", explanation: "Menunjukkan kesetaraan pembagian adil." },
        { term: "4", role: "Isi Tiap Wadah (Hasil)", explanation: "Banyak benda yang didapat setiap wadah." },
      ],
      note: "Pembagian berbagi rata mencari berapa isi setiap wadah jika jumlah wadah sudah diketahui.",
    },
    guidedPractice: {
      prompt: "Ada 15 pensil warna yang dibagikan rata kepada 5 anak. Berapa pensil yang didapat setiap anak?",
      a: 15,
      b: 5,
      answer: 3,
      hint: "15 dibagi ke dalam 5 kelompok: 5 anak × ? pensil = 15 pensil?",
      objectType: "pencil",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Berbagi ke 2 Anak",
        title: "6 Jeruk Dibagi ke 2 Piring",
        context: "Ada 6 buah jeruk dibagikan adil ke dalam 2 piring.",
        a: 6,
        b: 2,
        objectType: "orange",
        standardExpression: "6 ÷ 2 = 3",
        explanationNote: "Masing-masing piring mendapat 3 buah jeruk.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Berbagi ke 3 Wadah",
        title: "12 Pensil Dibagi ke 3 Kotak",
        context: "Ada 12 pensil dibagikan sama rata ke 3 wadah pensil.",
        a: 12,
        b: 3,
        objectType: "pencil",
        standardExpression: "12 ÷ 3 = 4",
        explanationNote: "3 wadah × 4 pensil = 12 pensil.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Berbagi ke 4 Toples",
        title: "16 Kue Dibagi ke 4 Toples",
        context: "Ada 16 kue biskuit dimasukkan adil ke dalam 4 toples.",
        a: 16,
        b: 4,
        objectType: "cookie",
        standardExpression: "16 ÷ 4 = 4",
        explanationNote: "Masing-masing toples berisi 4 potong kue.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Dibagikan ke 1 Anak",
        title: "5 Buku untuk 1 Anak",
        context: "Ada 5 buku cerita diberikan seluruhnya kepada 1 anak.",
        a: 5,
        b: 1,
        objectType: "book",
        standardExpression: "5 ÷ 1 = 5",
        explanationNote: "Setiap bilangan dibagi 1 hasilnya adalah bilangan itu sendiri.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Pensil Warna untuk Lomba",
        story: "Ibu guru memiliki 15 pensil warna baru. Pensil itu dibagikan sama rata kepada 5 siswa yang mengikuti lomba menggambar.",
        question: "Berapa pensil warna yang didapat oleh setiap siswa?",
        a: 15,
        b: 5,
        answer: 3,
        objectType: "pencil",
        hint: "15 pensil dibagi rata ke 5 siswa: 5 × ? = 15.",
        explanation: "15 ÷ 5 = 3 pensil untuk setiap anak.",
      },
      {
        id: "sp-2",
        title: "Jeruk Manis untuk Tamu",
        story: "Ada 12 buah jeruk manis di meja. Ibu membagikannya rata ke dalam 4 mangkuk saji untuk para tamu.",
        question: "Berapa buah jeruk di setiap mangkuk saji?",
        a: 12,
        b: 4,
        answer: 3,
        objectType: "orange",
        hint: "12 jeruk dibagi ke 4 mangkuk: 4 × ? = 12.",
        explanation: "12 ÷ 4 = 3 buah jeruk tiap mangkuk.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Pembagian Berbagi Rata",
      instructions: "Bagikan total benda sama rata ke sejumlah wadah yang ditentukan.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "visual",
          storyText: "Ada 15 pensil warna dibagikan rata ke 5 anak.",
          question: "Berapa pensil yang didapat setiap anak?",
          a: 15,
          b: 5,
          answer: 3,
          objectType: "pencil",
          unit: "pensil",
          hint: "15 ÷ 5 = ?",
        },
        {
          id: "ws-2",
          number: 2,
          type: "visual",
          storyText: "Ada 12 jeruk dibagikan sama rata ke 3 piring.",
          question: "Berapa jeruk isi tiap piring?",
          a: 12,
          b: 3,
          answer: 4,
          objectType: "orange",
          unit: "jeruk",
          hint: "12 ÷ 3 = ?",
        },
        {
          id: "ws-3",
          number: 3,
          type: "story",
          storyText: "Ada 16 potong kue biskuit dimasukkan rata ke 4 toples.",
          question: "Berapa biskuit isi tiap toples?",
          a: 16,
          b: 4,
          answer: 4,
          objectType: "cookie",
          unit: "kue",
          hint: "16 ÷ 4 = ?",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitunglah: 10 ÷ 2 = ...",
          a: 10,
          b: 2,
          answer: 5,
          hint: "2 × ? = 10",
        },
        {
          id: "ws-5",
          number: 5,
          type: "direct",
          question: "Hitunglah: 18 ÷ 3 = ...",
          a: 18,
          b: 3,
          answer: 6,
          hint: "3 × ? = 18",
        },
      ],
    },
  },
  {
    id: "div-grouping",
    operation: "division",
    title: "Pembagian sebagai Pengelompokan (Grouping)",
    subtitle: "Membentuk kelompok dengan isi tertentu",
    description: "Memahami pembagian sebagai mencari berapa banyak kelompok yang dapat dibentuk dengan kapasitas tertentu.",
    prerequisites: ["div-sharing"],
    representations: ["equal-groups", "array"],
    difficulty: 2,
    conceptTitle: "Berapa Kelompok yang Jadi?",
    conceptExplanation: "Ada 12 butir telur. Setiap wadah harus berisi 4 butir telur. Berapa wadah yang dibutuhkan? Kita memerlukan 3 wadah.",
    exampleA: 12,
    exampleB: 4,
    strategy: "grouping",
    objectType: "egg",
    mathForm: {
      title: "Bentuk Pembagian Pengelompokan",
      repeatedExpression: "12 = 4 + 4 + 4  (3 kelompok)",
      standardExpression: "12 ÷ 4 = 3",
      terms: [
        { term: "12", role: "Total Benda (Dividen)", explanation: "Seluruh benda yang akan dikelompokkan." },
        { term: "÷", role: "Tanda Bagi", explanation: "Dikelompokkan dengan kapasitas tertentu." },
        { term: "4", role: "Isi Tiap Kelompok (Pembagi)", explanation: "Kapasitas isi per kelompok." },
        { term: "=", role: "Sama Dengan", explanation: "Menunjukkan kesetaraan." },
        { term: "3", role: "Banyak Kelompok (Hasil)", explanation: "Jumlah kelompok yang terbentuk." },
      ],
      note: "Pembagian pengelompokan mencari berapa banyak kelompok yang bisa terbentuk dari kapasitas tertentu.",
    },
    guidedPractice: {
      prompt: "Ada 18 butir telur. Setiap wadah diisi 6 butir telur. Berapa wadah yang terisi penuh?",
      a: 18,
      b: 6,
      answer: 3,
      hint: "18 butir dikelompokkan per 6: 6, 12, 18. Jadi ada ? kelompok.",
      objectType: "egg",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Kemasan Telur",
        title: "12 Telur Dimasukkan per 4 Butir",
        context: "Ada 12 butir telur. Setiap kotak kemasan harus memuat 4 butir telur.",
        a: 12,
        b: 4,
        objectType: "egg",
        standardExpression: "12 ÷ 4 = 3",
        explanationNote: "Dibutuhkan 3 kotak untuk mengemas seluruh telur.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Kantong Apel",
        title: "15 Apel Dikemas per 5 Buah",
        context: "Ada 15 buah apel. Setiap kantong plastik diisi 5 buah apel segar.",
        a: 15,
        b: 5,
        objectType: "apple",
        standardExpression: "15 ÷ 5 = 3",
        explanationNote: "Terbentuk 3 kantong apel yang penuh.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Ikatan Pensil",
        title: "18 Pensil Diikat per 6 Batang",
        context: "Ada 18 pensil warna. Diikat dengan pita per 6 batang pensil.",
        a: 18,
        b: 6,
        objectType: "pencil",
        standardExpression: "18 ÷ 6 = 3",
        explanationNote: "Menghasilkan 3 ikatan pensil rapi.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Kotak Biskuit",
        title: "20 Biskuit Dikemas per 5 Keping",
        context: "Ibu memiliki 20 keping biskuit lezat. Setiap toples kecil diisi tepat 5 keping biskuit.",
        a: 20,
        b: 5,
        objectType: "cookie",
        standardExpression: "20 ÷ 5 = 4",
        explanationNote: "Dibutuhkan 4 toples kecil untuk menampung seluruh biskuit.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Wadah Telur Ayam",
        story: "Pak Tani mengumpulkan 18 butir telur dari kandang. Setiap wadah karton memuat 6 butir telur.",
        question: "Berapa wadah karton yang terisi penuh telur?",
        a: 18,
        b: 6,
        answer: 3,
        objectType: "egg",
        hint: "18 butir dikelompokkan per 6 butir: 6, 12, 18. Ada ? kelompok.",
        explanation: "18 ÷ 6 = 3 wadah karton.",
      },
      {
        id: "sp-2",
        title: "Bungkus Apel Manis",
        story: "Pedagang buah memiliki 20 buah apel. Ia membungkusnya ke dalam kantong, tiap kantong berisi 5 apel.",
        question: "Berapa banyak kantong apel yang dihasilkan?",
        a: 20,
        b: 5,
        answer: 4,
        objectType: "apple",
        hint: "20 dikelompokkan per 5: 5, 10, 15, 20. Berapa kantong?",
        explanation: "20 ÷ 5 = 4 kantong apel.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Pembagian Pengelompokan",
      instructions: "Tentukan berapa banyak kelompok yang terbentuk dengan kapasitas tertentu.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "visual",
          storyText: "Ada 18 butir telur. Setiap kotak diisi 6 butir telur.",
          question: "Berapa kotak yang terisi penuh?",
          a: 18,
          b: 6,
          answer: 3,
          objectType: "egg",
          unit: "kotak",
          hint: "18 ÷ 6 = ?",
        },
        {
          id: "ws-2",
          number: 2,
          type: "visual",
          storyText: "Ada 12 apel. Dimasukkan ke kantong per 4 apel.",
          question: "Berapa kantong yang dibutuhkan?",
          a: 12,
          b: 4,
          answer: 3,
          objectType: "apple",
          unit: "kantong",
          hint: "12 ÷ 4 = ?",
        },
        {
          id: "ws-3",
          number: 3,
          type: "story",
          storyText: "Paman punya 15 kue. Setiap piring disajikan 5 kue.",
          question: "Berapa piring yang dibutuhkan?",
          a: 15,
          b: 5,
          answer: 3,
          objectType: "cookie",
          unit: "piring",
          hint: "15 ÷ 5 = ?",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Hitunglah: 16 ÷ 4 = ...",
          a: 16,
          b: 4,
          answer: 4,
          hint: "16 dikelompokkan per 4",
        },
        {
          id: "ws-5",
          number: 5,
          type: "direct",
          question: "Hitunglah: 24 ÷ 6 = ...",
          a: 24,
          b: 6,
          answer: 4,
          hint: "6 × ? = 24",
        },
      ],
    },
  },
  {
    id: "div-fact-families",
    operation: "division",
    title: "Keluarga Fakta (Fact Family)",
    subtitle: "Hubungan timbal balik antara perkalian dan pembagian",
    description: "Memahami bahwa pembagian adalah kebalikan langsung dari perkalian.",
    prerequisites: ["div-grouping"],
    representations: ["array"],
    difficulty: 3,
    conceptTitle: "Perkalian dan Pembagian Saling Berhubungan",
    conceptExplanation: "Jika 4 × 3 = 12, maka secara otomatis 12 ÷ 3 = 4 dan 12 ÷ 4 = 3.",
    exampleA: 24,
    exampleB: 6,
    strategy: "multiplication-inverse",
    objectType: "motorcycle",
    mathForm: {
      title: "Keluarga Fakta Kali & Bagi",
      repeatedExpression: "4 × 6 = 24  ⟺  24 ÷ 6 = 4",
      standardExpression: "24 ÷ 6 = 4",
      terms: [
        { term: "24", role: "Keseluruhan", explanation: "Hasil kali dari 4 dan 6." },
        { term: "÷", role: "Operasi Kebalikan", explanation: "Mencari faktor pengali yang belum diketahui." },
        { term: "6", role: "Faktor Pengali", explanation: "Faktor yang diketahui." },
        { term: "=", role: "Sama Dengan", explanation: "Menunjukkan kesetaraan." },
        { term: "4", role: "Faktor Pasangan", explanation: "Nilai yang jika dikalikan 6 menghasilkan 24." },
      ],
      note: "Menghafal perkalian otomatis membantu menyelesaikan pembagian dengan cepat.",
    },
    guidedPractice: {
      prompt: "Karena 7 × 4 = 28, berapakah 28 ÷ 7?",
      a: 28,
      b: 7,
      answer: 4,
      hint: "Ingat kembali pasangan perkalian: 7 dikali berapa menghasilkan 28?",
      objectType: "pencil",
    },
    examples: [
      {
        id: "ex-1",
        badge: "Kondisi 1: Baris Motor 24 ÷ 6",
        title: "Parkiran Motor: 24 Dibagi 6 Baris",
        context: "Sebanyak 24 sepeda motor ditata rapi dalam 6 kolom sama panjang. Karena 4 × 6 = 24, terdapat 4 baris motor.",
        a: 24,
        b: 6,
        objectType: "motorcycle",
        repeatedExpression: "4 × 6 = 24  ⟺  24 ÷ 6 = 4",
        standardExpression: "24 ÷ 6 = 4",
        explanationNote: "Keluarga fakta: 4 × 6 = 24, sehingga 24 ÷ 6 = 4.",
      },
      {
        id: "ex-2",
        badge: "Kondisi 2: Susunan Buku 15 ÷ 3",
        title: "Rak Perpustakaan: 15 Dibagi 3",
        context: "Ada 15 buku yang ditata ke dalam 3 baris rak. Karena 5 × 3 = 15, setiap baris memuat 5 buku.",
        a: 15,
        b: 3,
        objectType: "book",
        repeatedExpression: "5 × 3 = 15  ⟺  15 ÷ 3 = 5",
        standardExpression: "15 ÷ 3 = 5",
        explanationNote: "Keluarga fakta: 5 × 3 = 15, sehingga 15 ÷ 3 = 5.",
      },
      {
        id: "ex-3",
        badge: "Kondisi 3: Baris Pensil 18 ÷ 3",
        title: "Kotak Pensil: 18 Dibagi 3",
        context: "Sebanyak 18 batang pensil disusun dalam 3 baris. Karena 6 × 3 = 18, setiap baris ada 6 pensil.",
        a: 18,
        b: 3,
        objectType: "pencil",
        repeatedExpression: "6 × 3 = 18  ⟺  18 ÷ 3 = 6",
        standardExpression: "18 ÷ 3 = 6",
        explanationNote: "Keluarga fakta: 6 × 3 = 18, sehingga 18 ÷ 3 = 6.",
      },
      {
        id: "ex-4",
        badge: "Kondisi 4: Baris Mobil 20 ÷ 5",
        title: "Garasi Toko: 20 Dibagi 5",
        context: "Ada 20 mobil baru ditata dalam baris berisi 5 mobil. Karena 4 × 5 = 20, terbentuk 4 baris mobil.",
        a: 20,
        b: 5,
        objectType: "car",
        repeatedExpression: "4 × 5 = 20  ⟺  20 ÷ 5 = 4",
        standardExpression: "20 ÷ 5 = 4",
        explanationNote: "Keluarga fakta: 4 × 5 = 20, sehingga 20 ÷ 5 = 4.",
      },
    ],
    storyProblems: [
      {
        id: "sp-1",
        title: "Pensil Warna di Meja Belajar",
        story: "Sebanyak 18 pensil warna ditata rapi dalam 3 baris susunan yang sama banyak di atas meja belajar.",
        question: "Berapa banyak pensil warna pada setiap baris?",
        a: 18,
        b: 3,
        answer: 6,
        objectType: "pencil",
        hint: "Pikirkan perkalian pasangan: 3 dikali berapa menghasilkan 18? 3 × 6 = 18.",
        explanation: "18 pensil ÷ 3 baris = 6 pensil warna di setiap baris.",
      },
      {
        id: "sp-2",
        title: "Barisan Mobil di Gedung Parkir",
        story: "Sebuah gedung parkir menampung 20 mobil dalam beberapa baris yang sama. Jika setiap baris berisi 5 mobil, berapa baris mobil yang terparkir?",
        question: "Berapa baris mobil yang terparkir di gedung tersebut?",
        a: 20,
        b: 5,
        answer: 4,
        objectType: "car",
        hint: "Berapa kali 5 menghasilkan 20? 5 × 4 = 20.",
        explanation: "20 mobil ÷ 5 mobil per baris = 4 baris mobil.",
      },
    ],
    worksheet: {
      title: "Lembar Kerja Siswa: Keluarga Fakta (Fact Family)",
      instructions: "Gunakan hubungan kebalikan antara perkalian dan pembagian untuk mencari jawabannya.",
      items: [
        {
          id: "ws-1",
          number: 1,
          type: "visual",
          storyText: "12 mobil ditata dalam 3 baris rapi di tempat parkir.",
          question: "Berapa banyak mobil pada setiap baris?",
          a: 12,
          b: 3,
          answer: 4,
          objectType: "car",
          unit: "mobil",
          hint: "3 baris × ? mobil = 12 mobil. 12 ÷ 3 = 4.",
        },
        {
          id: "ws-2",
          number: 2,
          type: "visual",
          storyText: "16 buku disusun dalam 4 baris yang sama banyak di rak.",
          question: "Berapa banyak buku pada tiap baris?",
          a: 16,
          b: 4,
          answer: 4,
          objectType: "book",
          unit: "buku",
          hint: "4 baris × 4 buku = 16 buku. 16 ÷ 4 = 4.",
        },
        {
          id: "ws-3",
          number: 3,
          type: "story",
          storyText: "Sebanyak 24 sepeda motor diparkir dalam 4 baris sama banyak.",
          question: "Berapa banyak sepeda motor pada setiap baris?",
          a: 24,
          b: 4,
          answer: 6,
          objectType: "motorcycle",
          unit: "motor",
          hint: "4 × ? = 24. 24 ÷ 4 = 6.",
        },
        {
          id: "ws-4",
          number: 4,
          type: "direct",
          question: "Gunakan fakta perkalian: Karena 3 × 7 = 21, maka 21 ÷ 3 = ...",
          a: 21,
          b: 3,
          answer: 7,
          hint: "21 ÷ 3 = 7",
        },
        {
          id: "ws-5",
          number: 5,
          type: "direct",
          question: "Gunakan fakta perkalian: Karena 5 × 6 = 30, maka 30 ÷ 5 = ...",
          a: 30,
          b: 5,
          answer: 6,
          hint: "30 ÷ 5 = 6",
        },
      ],
    },
  },
  ...COLUMN_SKILLS,
];

export function getSkillsByOperation(operation: Operation): Skill[] {
  return INITIAL_SKILLS.filter((s) => s.operation === operation);
}

export function getSkillById(id: string): Skill | undefined {
  return INITIAL_SKILLS.find((s) => s.id === id);
}

export function getAllSkills(): Skill[] {
  return INITIAL_SKILLS;
}
